/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MementoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_TIMELINE_FILTERS = {
  search: "",
  source: "all",
  sourceId: "",
  dateRange: "upcoming",
  includeCompleted: false,
  includeArchived: false
};
var DEFAULT_SETTINGS = {
  events: [],
  externalCalendarSources: [],
  externalEventsCache: [],
  hiddenExternalEventIds: [],
  timelineFilters: DEFAULT_TIMELINE_FILTERS,
  timelineViewMode: "all",
  showPastEventsInSettings: false,
  eventNoteFolder: "",
  frontmatterLanguage: "en"
};
var VIEW_TYPE_TIMELINE = "memento-timeline";
var RECURRENCE_LABELS = {
  none: "One-time",
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
  yearly: "Yearly"
};
function generateId() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === "x" ? r : r & 3 | 8;
    return v.toString(16);
  });
}
function formatDateDisplay(dateStr) {
  const date = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
  const mainDate = date.toLocaleDateString(void 0, {
    year: "numeric",
    month: "long",
    day: "numeric"
  });
  const weekday = date.toLocaleDateString(void 0, {
    weekday: "long"
  });
  return `${mainDate} (${weekday})`;
}
function formatTimeDisplay(time) {
  if (!time) return "";
  const [h, m] = time.split(":").map(Number);
  if (h === void 0 || m === void 0 || Number.isNaN(h) || Number.isNaN(m))
    return time;
  const ampm = h >= 12 ? "PM" : "AM";
  const hour12 = h % 12 || 12;
  return `${hour12}:${m.toString().padStart(2, "0")} ${ampm}`;
}
function getTodayStr() {
  return dateToStr(/* @__PURE__ */ new Date());
}
function normalizeEvent(event) {
  return {
    ...event,
    recurrence: event.recurrence || "none",
    recurrenceInterval: Math.max(1, event.recurrenceInterval || 1),
    status: event.status || "active",
    notePaths: event.notePaths || {},
    updatedAt: event.updatedAt || event.createdAt
  };
}
function getRecurrenceLabel(event) {
  if (event.recurrence === "none") return RECURRENCE_LABELS.none;
  const interval = Math.max(1, event.recurrenceInterval || 1);
  const unitLabels = {
    daily: "day",
    weekly: "week",
    monthly: "month",
    yearly: "year"
  };
  const base = interval === 1 ? RECURRENCE_LABELS[event.recurrence] : `Every ${interval} ${unitLabels[event.recurrence]}${interval > 1 ? "s" : ""}`;
  if (event.recurrenceEndDate) return `${base} until ${event.recurrenceEndDate}`;
  if (event.recurrenceCount) return `${base} (${event.recurrenceCount} times)`;
  return base;
}
function getRecurrenceOccurrences(event, startRange, endRange) {
  if (event.recurrence === "none") {
    if (event.date >= startRange && event.date <= endRange) {
      return [event.date];
    }
    return [];
  }
  const occurrences = [];
  const eventDate = /* @__PURE__ */ new Date(event.date + "T00:00:00");
  const rangeStart = /* @__PURE__ */ new Date(startRange + "T00:00:00");
  const rangeEnd = /* @__PURE__ */ new Date(endRange + "T00:00:00");
  const recurrenceEnd = event.recurrenceEndDate ? /* @__PURE__ */ new Date(event.recurrenceEndDate + "T00:00:00") : null;
  const interval = Math.max(1, event.recurrenceInterval || 1);
  let current = new Date(eventDate);
  let generatedCount = 0;
  while (current < rangeStart) {
    generatedCount++;
    if (event.recurrenceCount && generatedCount >= event.recurrenceCount) {
      return [];
    }
    current = advanceDate(current, event.recurrence, eventDate, interval);
  }
  const maxIterations = 1500;
  let iterations = 0;
  while (current <= rangeEnd && iterations < maxIterations) {
    if (recurrenceEnd && current > recurrenceEnd) break;
    generatedCount++;
    if (!event.recurrenceCount || generatedCount <= event.recurrenceCount) {
      occurrences.push(dateToStr(current));
    }
    if (event.recurrenceCount && generatedCount >= event.recurrenceCount) break;
    current = advanceDate(current, event.recurrence, eventDate, interval);
    iterations++;
  }
  return occurrences;
}
function advanceDate(current, recurrence, originalDate, interval) {
  const next = new Date(current);
  switch (recurrence) {
    case "daily":
      next.setDate(next.getDate() + interval);
      break;
    case "weekly":
      next.setDate(next.getDate() + 7 * interval);
      break;
    case "monthly": {
      const origDay = originalDate.getDate();
      next.setMonth(next.getMonth() + interval);
      if (next.getDate() !== origDay) {
        next.setDate(0);
      }
      break;
    }
    case "yearly": {
      const origDay = originalDate.getDate();
      next.setFullYear(next.getFullYear() + interval);
      if (next.getDate() !== origDay) {
        next.setDate(0);
      }
      break;
    }
    default:
      next.setFullYear(next.getFullYear() + 100);
      break;
  }
  return next;
}
function dateToStr(d) {
  return `${d.getFullYear()}-${(d.getMonth() + 1).toString().padStart(2, "0")}-${d.getDate().toString().padStart(2, "0")}`;
}
function addDays(dateStr, days) {
  const d = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
  d.setDate(d.getDate() + days);
  return dateToStr(d);
}
function getTimelineRange(viewMode, filters = DEFAULT_TIMELINE_FILTERS) {
  const today = getTodayStr();
  const startDate = filters.dateRange === "all" ? "0000-01-01" : today;
  let endDate;
  if (filters.dateRange === "week") {
    endDate = addDays(today, 7);
  } else if (filters.dateRange === "month" || viewMode === "month") {
    const d = /* @__PURE__ */ new Date();
    d.setMonth(d.getMonth() + 1);
    endDate = dateToStr(d);
  } else {
    const d = /* @__PURE__ */ new Date();
    d.setFullYear(d.getFullYear() + 2);
    endDate = dateToStr(d);
  }
  return { startDate, endDate };
}
function getTimelineEntries(events, viewMode, externalEvents = [], filters = DEFAULT_TIMELINE_FILTERS, externalSources = [], hiddenExternalEventIds = []) {
  const { startDate, endDate } = getTimelineRange(viewMode, filters);
  const entries = [];
  for (const rawEvent of events) {
    const event = normalizeEvent(rawEvent);
    if (!shouldShowManualEvent(event, filters)) continue;
    const occurrences = getRecurrenceOccurrences(event, startDate, endDate);
    for (const date of occurrences) {
      entries.push({
        id: `${event.id}:${date}`,
        sourceType: "memento",
        sourceId: "memento",
        sourceName: "Memento",
        event,
        occurrenceDate: date,
        occurrenceTime: event.time,
        editable: true
      });
    }
  }
  const enabledSourceIds = new Set(
    externalSources.filter((source) => source.enabled).map((source) => source.id)
  );
  for (const event of externalEvents) {
    if (hiddenExternalEventIds.includes(event.id)) continue;
    if (!enabledSourceIds.has(event.sourceId)) continue;
    if (!shouldShowExternalEvent(event, filters)) continue;
    const source = externalSources.find((item) => item.id === event.sourceId);
    const occurrences = getRecurrenceOccurrences(event, startDate, endDate);
    for (const date of occurrences) {
      entries.push({
        id: `${event.id}:${date}`,
        sourceType: "external",
        sourceId: event.sourceId,
        sourceName: source?.name || "External calendar",
        event,
        occurrenceDate: date,
        occurrenceTime: event.time,
        editable: false
      });
    }
  }
  entries.sort((a, b) => {
    const dateCmp = a.occurrenceDate.localeCompare(b.occurrenceDate);
    if (dateCmp !== 0) return dateCmp;
    return a.occurrenceTime.localeCompare(b.occurrenceTime);
  });
  return entries;
}
function shouldShowManualEvent(event, filters) {
  if (filters.source === "external") return false;
  if (filters.sourceId && filters.sourceId !== "memento") return false;
  if (event.status === "completed" && !filters.includeCompleted) return false;
  if (event.status === "archived" && !filters.includeArchived) return false;
  return matchesSearch(event, filters.search);
}
function shouldShowExternalEvent(event, filters) {
  if (filters.source === "memento") return false;
  if (filters.sourceId && filters.sourceId !== event.sourceId) return false;
  return matchesSearch(event, filters.search);
}
function matchesSearch(event, query) {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) return true;
  const haystack = `${event.title} ${event.context} ${event.location || ""}`.toLowerCase();
  return haystack.includes(trimmed);
}
function getEventDatesSet(events, lookaheadDays, externalEvents = [], externalSources = [], hiddenExternalEventIds = []) {
  const endDate = /* @__PURE__ */ new Date();
  endDate.setDate(endDate.getDate() + lookaheadDays);
  const endStr = dateToStr(endDate);
  const startDate = /* @__PURE__ */ new Date();
  startDate.setDate(1);
  startDate.setMonth(startDate.getMonth() - 1);
  const startStr = dateToStr(startDate);
  const dates = /* @__PURE__ */ new Set();
  const enabledSourceIds = new Set(
    externalSources.filter((source) => source.enabled).map((source) => source.id)
  );
  for (const rawEvent of events) {
    const event = normalizeEvent(rawEvent);
    if (event.status === "archived" || event.status === "completed") continue;
    const occurrences = getRecurrenceOccurrences(event, startStr, endStr);
    for (const date of occurrences) {
      dates.add(date);
    }
  }
  for (const event of externalEvents) {
    if (hiddenExternalEventIds.includes(event.id)) continue;
    if (!enabledSourceIds.has(event.sourceId)) continue;
    const occurrences = getRecurrenceOccurrences(event, startStr, endStr);
    for (const date of occurrences) {
      dates.add(date);
    }
  }
  return dates;
}

// src/EventModal.ts
var import_obsidian = require("obsidian");
var EventModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit, existingEvent, prefilledDate) {
    super(app);
    this.onSubmit = onSubmit;
    this.isEditing = !!existingEvent;
    if (existingEvent) {
      this.event = { ...existingEvent };
    } else {
      this.event = {
        id: generateId(),
        date: prefilledDate || getTodayStr(),
        time: "",
        title: "",
        context: "",
        recurrence: "none",
        recurrenceInterval: 1,
        status: "active",
        notePaths: {},
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        updatedAt: (/* @__PURE__ */ new Date()).toISOString()
      };
    }
  }
  onOpen() {
    const { contentEl, modalEl } = this;
    contentEl.addClass("memento-modal");
    modalEl.addClass("memento-modal-container");
    contentEl.addEventListener("focusin", (e) => {
      if (!activeDocument.body.classList.contains("is-mobile")) return;
      const target = e.target;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) {
        const scrollTarget = target.closest(".setting-item") || target;
        window.setTimeout(() => {
          const containerRect = contentEl.getBoundingClientRect();
          const targetRect = scrollTarget.getBoundingClientRect();
          const offset = window.innerHeight * 0.2;
          contentEl.scrollTo({
            top: contentEl.scrollTop + (targetRect.top - containerRect.top) - offset,
            behavior: "smooth"
          });
        }, 300);
      }
    });
    const header = contentEl.createDiv({ cls: "memento-modal-header" });
    header.createEl("h2", {
      text: this.isEditing ? "Edit Event" : "Create Event",
      cls: "memento-modal-title"
    });
    const dateBadge = header.createDiv({ cls: "memento-date-badge" });
    const updateDateBadge = () => {
      dateBadge.empty();
      dateBadge.createSpan({
        text: formatDateDisplay(this.event.date || getTodayStr()),
        cls: "memento-date-badge-text"
      });
    };
    updateDateBadge();
    const form = contentEl.createDiv({ cls: "memento-form" });
    new import_obsidian.Setting(form).setName("Date").setDesc("When does this event occur?").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.event.date || getTodayStr());
      text.onChange((value) => {
        this.event.date = value;
        updateDateBadge();
      });
      text.inputEl.addClass("memento-date-input");
    });
    new import_obsidian.Setting(form).setName("End date").setDesc("Optional end date for longer events").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.event.endDate || "");
      text.onChange((value) => {
        this.event.endDate = value || void 0;
      });
      text.inputEl.addClass("memento-date-input");
    });
    let currentHour = "--";
    let currentMin = "--";
    if (this.event.time) {
      const [h, m] = this.event.time.split(":");
      currentHour = h;
      currentMin = m;
    }
    const timeSetting = new import_obsidian.Setting(form).setName("Time").setDesc("What time? (optional)");
    timeSetting.addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "23";
      text.inputEl.placeholder = "HH";
      text.inputEl.setCssStyles({ width: "4rem", textAlign: "center" });
      text.setValue(currentHour !== "--" ? currentHour : "");
      text.onChange((value) => {
        let val = parseInt(value, 10);
        if (isNaN(val)) {
          currentHour = "--";
        } else {
          if (val < 0) val = 0;
          if (val > 23) val = 23;
          currentHour = val.toString().padStart(2, "0");
          text.setValue(currentHour);
        }
        updateTime();
      });
    });
    const separator = timeSetting.controlEl.createSpan({
      text: " : ",
      cls: "memento-time-separator"
    });
    separator.setCssStyles({ margin: "0 0.2rem", fontWeight: "bold" });
    timeSetting.addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "59";
      text.inputEl.placeholder = "MM";
      text.inputEl.setCssStyles({ width: "4rem", textAlign: "center" });
      text.setValue(currentMin !== "--" ? currentMin : "");
      text.onChange((value) => {
        let val = parseInt(value, 10);
        if (isNaN(val)) {
          currentMin = "--";
        } else {
          if (val < 0) val = 0;
          if (val > 59) val = 59;
          currentMin = val.toString().padStart(2, "0");
          text.setValue(currentMin);
        }
        updateTime();
      });
    });
    const updateTime = () => {
      if (currentHour === "--" && currentMin === "--") {
        this.event.time = "";
      } else {
        const h = currentHour === "--" ? "12" : currentHour;
        const m = currentMin === "--" ? "00" : currentMin;
        this.event.time = `${h}:${m}`;
      }
    };
    let currentEndHour = "--";
    let currentEndMin = "--";
    if (this.event.endTime) {
      const [h, m] = this.event.endTime.split(":");
      currentEndHour = h;
      currentEndMin = m;
    }
    const endTimeSetting = new import_obsidian.Setting(form).setName("End time").setDesc("Optional end time");
    endTimeSetting.addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "23";
      text.inputEl.placeholder = "HH";
      text.inputEl.setCssStyles({ width: "4rem", textAlign: "center" });
      text.setValue(currentEndHour !== "--" ? currentEndHour : "");
      text.onChange((value) => {
        let val = parseInt(value, 10);
        if (isNaN(val)) {
          currentEndHour = "--";
        } else {
          if (val < 0) val = 0;
          if (val > 23) val = 23;
          currentEndHour = val.toString().padStart(2, "0");
          text.setValue(currentEndHour);
        }
        updateEndTime();
      });
    });
    endTimeSetting.controlEl.createSpan({
      text: " : ",
      cls: "memento-time-separator"
    }).setCssStyles({ margin: "0 0.2rem", fontWeight: "bold" });
    endTimeSetting.addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "59";
      text.inputEl.placeholder = "MM";
      text.inputEl.setCssStyles({ width: "4rem", textAlign: "center" });
      text.setValue(currentEndMin !== "--" ? currentEndMin : "");
      text.onChange((value) => {
        let val = parseInt(value, 10);
        if (isNaN(val)) {
          currentEndMin = "--";
        } else {
          if (val < 0) val = 0;
          if (val > 59) val = 59;
          currentEndMin = val.toString().padStart(2, "0");
          text.setValue(currentEndMin);
        }
        updateEndTime();
      });
    });
    const updateEndTime = () => {
      if (currentEndHour === "--" && currentEndMin === "--") {
        this.event.endTime = "";
      } else {
        const h = currentEndHour === "--" ? "12" : currentEndHour;
        const m = currentEndMin === "--" ? "00" : currentEndMin;
        this.event.endTime = `${h}:${m}`;
      }
    };
    let titleInput;
    new import_obsidian.Setting(form).setName("Title").setDesc("Give your event a name").addText((text) => {
      text.setPlaceholder("e.g. Team standup, Dentist appointment...");
      text.setValue(this.event.title || "");
      text.onChange((value) => {
        this.event.title = value;
      });
      titleInput = text.inputEl;
      titleInput.addClass("memento-title-input");
    });
    new import_obsidian.Setting(form).setName("Context").setDesc("Additional details about the event").addTextArea((text) => {
      text.setPlaceholder("Add context, notes, or details...");
      text.setValue(this.event.context || "");
      text.onChange((value) => {
        this.event.context = value;
      });
      text.inputEl.addClass("memento-context-input");
      text.inputEl.rows = 3;
    });
    new import_obsidian.Setting(form).setName("Recurrence").setDesc("Does this event repeat?").addDropdown((dropdown) => {
      for (const [value, label] of Object.entries(RECURRENCE_LABELS)) {
        dropdown.addOption(value, label);
      }
      dropdown.setValue(this.event.recurrence || "none");
      dropdown.onChange((value) => {
        this.event.recurrence = value;
      });
    });
    new import_obsidian.Setting(form).setName("Repeat interval").setDesc("Use 1 for every day/week/month/year, 2 for every other, etc.").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "1";
      text.setValue((this.event.recurrenceInterval || 1).toString());
      text.onChange((value) => {
        const parsed = parseInt(value, 10);
        this.event.recurrenceInterval = Number.isNaN(parsed) || parsed < 1 ? 1 : parsed;
      });
    });
    new import_obsidian.Setting(form).setName("Repeat until").setDesc("Optional recurrence end date").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.event.recurrenceEndDate || "");
      text.onChange((value) => {
        this.event.recurrenceEndDate = value || void 0;
      });
    });
    new import_obsidian.Setting(form).setName("Repeat count").setDesc("Optional maximum number of occurrences").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "1";
      text.setValue(this.event.recurrenceCount?.toString() || "");
      text.onChange((value) => {
        const parsed = parseInt(value, 10);
        this.event.recurrenceCount = Number.isNaN(parsed) || parsed < 1 ? void 0 : parsed;
      });
    });
    new import_obsidian.Setting(form).setName("Status").setDesc("Completed and archived events are hidden unless enabled").addDropdown((dropdown) => {
      dropdown.addOption("active", "Active").addOption("completed", "Completed").addOption("archived", "Archived").setValue(this.event.status || "active").onChange((value) => {
        this.event.status = value;
      });
    });
    const buttonRow = contentEl.createDiv({ cls: "memento-button-row" });
    const cancelBtn = buttonRow.createEl("button", {
      text: "Cancel",
      cls: "memento-btn memento-btn-secondary"
    });
    cancelBtn.addEventListener("click", () => this.close());
    const submitBtn = buttonRow.createEl("button", {
      text: this.isEditing ? "Save Changes" : "Create Event",
      cls: "memento-btn memento-btn-primary"
    });
    submitBtn.addEventListener("click", () => this.handleSubmit());
    window.setTimeout(() => {
      if (titleInput) titleInput.focus();
    }, 50);
    this.scope.register([], "Enter", (e) => {
      if (activeDocument.activeElement?.tagName !== "TEXTAREA") {
        e.preventDefault();
        this.handleSubmit();
      }
    });
  }
  handleSubmit() {
    if (!this.event.title?.trim()) {
      this.contentEl.addClass("memento-shake");
      window.setTimeout(() => this.contentEl.removeClass("memento-shake"), 500);
      return;
    }
    const fullEvent = {
      id: this.event.id || generateId(),
      date: this.event.date || getTodayStr(),
      time: this.event.time || "",
      endDate: this.event.endDate || void 0,
      endTime: this.event.endTime || "",
      title: this.event.title.trim(),
      context: this.event.context?.trim() || "",
      recurrence: this.event.recurrence || "none",
      recurrenceInterval: Math.max(1, this.event.recurrenceInterval || 1),
      recurrenceEndDate: this.event.recurrenceEndDate || void 0,
      recurrenceCount: this.event.recurrenceCount,
      status: this.event.status || "active",
      notePaths: this.event.notePaths || {},
      createdAt: this.event.createdAt || (/* @__PURE__ */ new Date()).toISOString(),
      updatedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
    this.onSubmit(fullEvent);
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/TimelineView.ts
var import_obsidian2 = require("obsidian");
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, title, message, onConfirm, confirmText = "Confirm", isWarning = false) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
    this.confirmText = confirmText;
    this.isWarning = isWarning;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    ).addButton((btn) => {
      btn.setButtonText(this.confirmText).onClick(() => {
        this.close();
        this.onConfirm();
      });
      if (this.isWarning) {
        btn.setDestructive();
      } else {
        btn.setCta();
      }
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var EventActionModal = class extends import_obsidian2.Modal {
  constructor(app, entry, noteExists, actions) {
    super(app);
    this.entry = entry;
    this.noteExists = noteExists;
    this.actions = actions;
  }
  onOpen() {
    const { contentEl } = this;
    const event = this.entry.event;
    contentEl.addClass("memento-action-modal");
    contentEl.createEl("h2", { text: event.title });
    contentEl.createEl("p", {
      text: `${formatDateDisplay(this.entry.occurrenceDate)}${this.entry.occurrenceTime ? ` at ${formatTimeDisplay(this.entry.occurrenceTime)}` : ""}`,
      cls: "setting-item-description"
    });
    contentEl.createEl("p", {
      text: this.entry.sourceName,
      cls: "memento-action-source"
    });
    if (event.context) {
      contentEl.createEl("p", { text: event.context });
    }
    if (isExternalEvent(event) && event.location) {
      contentEl.createEl("p", { text: event.location, cls: "setting-item-description" });
    }
    const setting = new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    );
    if (this.entry.editable) {
      setting.addButton(
        (btn) => btn.setButtonText("Edit Event").onClick(() => {
          this.close();
          this.actions.edit();
        })
      ).addButton(
        (btn) => btn.setButtonText("Duplicate").onClick(() => {
          this.close();
          this.actions.duplicate();
        })
      ).addButton(
        (btn) => btn.setButtonText("Complete").onClick(() => {
          this.close();
          this.actions.complete();
        })
      ).addButton(
        (btn) => btn.setButtonText("Archive").onClick(() => {
          this.close();
          this.actions.archive();
        })
      );
    } else {
      setting.addButton(
        (btn) => btn.setButtonText("Import").onClick(() => {
          this.close();
          this.actions.importExternal();
        })
      ).addButton(
        (btn) => btn.setButtonText("Hide").onClick(() => {
          this.close();
          this.actions.hideExternal();
        })
      );
    }
    setting.addButton(
      (btn) => btn.setButtonText("Copy").onClick(() => {
        this.actions.copyDetails();
      })
    ).addButton((btn) => {
      btn.setButtonText(this.noteExists ? "Open Note" : "Create Note").setCta().onClick(() => {
        this.close();
        this.actions.openNote();
      });
    });
    this.scope.register([], "e", () => {
      if (!this.entry.editable) return false;
      this.close();
      this.actions.edit();
      return false;
    });
    this.scope.register([], "n", () => {
      this.close();
      this.actions.openNote();
      return false;
    });
    this.scope.register([], "d", () => {
      if (!this.entry.editable) return false;
      this.close();
      this.actions.duplicate();
      return false;
    });
    this.scope.register([], "a", () => {
      if (!this.entry.editable) return false;
      this.close();
      this.actions.archive();
      return false;
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TimelineView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.shouldRestoreSearchFocus = false;
    this.searchCursorPosition = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TIMELINE;
  }
  getDisplayText() {
    return "Event Timeline";
  }
  getIcon() {
    return "calendar-clock";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("memento-timeline-container");
    this.renderFilters(contentEl);
    const entries = getTimelineEntries(
      this.plugin.settings.events,
      this.plugin.settings.timelineViewMode,
      this.plugin.settings.externalEventsCache,
      this.plugin.settings.timelineFilters,
      this.plugin.settings.externalCalendarSources,
      this.plugin.settings.hiddenExternalEventIds
    );
    if (entries.length === 0) {
      this.renderEmptyState(contentEl);
      return;
    }
    const timelineWrapper = contentEl.createDiv({
      cls: "memento-timeline-wrapper"
    });
    const ul = timelineWrapper.createEl("ul", { cls: "memento-timeline" });
    for (const entry of entries) {
      this.renderEntry(ul, entry);
    }
  }
  renderFilters(container) {
    const filters = this.plugin.settings.timelineFilters;
    const controls = container.createDiv({ cls: "memento-timeline-controls" });
    const headerRow = controls.createDiv({ cls: "memento-search-header" });
    headerRow.createSpan({ cls: "memento-filters-label", text: "Filters" });
    const searchButton = headerRow.createEl("button", {
      cls: "memento-search-button",
      attr: { type: "button" }
    });
    const filtersBody = controls.createDiv({ cls: "memento-filters-body" });
    const searchArea = filtersBody.createDiv({ cls: "memento-search-area" });
    const searchInput = searchArea.createEl("input", {
      type: "search",
      placeholder: "Search events",
      cls: "memento-search-input"
    });
    searchInput.value = filters.search;
    const clearButton = searchArea.createEl("button", {
      cls: "memento-search-clear",
      attr: { type: "button", "aria-label": "Clear search" }
    });
    clearButton.textContent = "\xD7";
    const filtersGroup = filtersBody.createDiv({ cls: "memento-filters-group" });
    const hasActiveFilters = filters.search.trim().length > 0 || filters.source !== "all" || filters.sourceId !== "" || filters.dateRange !== "upcoming" || filters.includeCompleted || filters.includeArchived;
    const applyVisibility = (visible, options = {}) => {
      filtersBody.toggleClass("is-visible", visible);
      searchButton.toggleClass("is-active", visible);
      searchButton.textContent = visible ? "Hide filters" : "Show filters";
      if (!visible) {
        searchInput.blur();
        this.shouldRestoreSearchFocus = false;
        this.searchCursorPosition = null;
      } else if (options.focus) {
        window.setTimeout(() => {
          searchInput.focus({ preventScroll: true });
          if (this.searchCursorPosition !== null) {
            const pos = this.searchCursorPosition;
            searchInput.setSelectionRange(pos, pos);
          }
          this.shouldRestoreSearchFocus = false;
          this.searchCursorPosition = null;
        }, 0);
      }
    };
    applyVisibility(hasActiveFilters, {
      focus: this.shouldRestoreSearchFocus
    });
    searchButton.addEventListener("click", () => {
      const shouldShow = !filtersBody.hasClass("is-visible");
      applyVisibility(shouldShow, { focus: shouldShow });
    });
    searchInput.addEventListener("input", (event) => {
      const target = event.target;
      filters.search = target.value;
      this.shouldRestoreSearchFocus = true;
      this.searchCursorPosition = target.selectionStart ?? target.value.length;
      void this.plugin.saveSettings();
    });
    clearButton.addEventListener("click", () => {
      if (searchInput.value.length > 0) {
        searchInput.value = "";
        filters.search = "";
        this.shouldRestoreSearchFocus = true;
        this.searchCursorPosition = 0;
        void this.plugin.saveSettings();
      } else {
        applyVisibility(false);
      }
    });
    new import_obsidian2.Setting(filtersGroup).setName("Source").addDropdown((dropdown) => {
      dropdown.addOption("all", "All sources").addOption("memento", "Memento only").addOption("external", "External only").setValue(filters.source).onChange((value) => {
        filters.source = value;
        filters.sourceId = "";
        this.shouldRestoreSearchFocus = true;
        this.searchCursorPosition = null;
        void this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(filtersGroup).setName("Calendar").addDropdown((dropdown) => {
      dropdown.addOption("", "Any calendar");
      dropdown.addOption("memento", "Memento");
      for (const source of this.plugin.settings.externalCalendarSources) {
        dropdown.addOption(source.id, source.name);
      }
      dropdown.setValue(filters.sourceId);
      dropdown.onChange((value) => {
        filters.sourceId = value;
        this.shouldRestoreSearchFocus = true;
        this.searchCursorPosition = null;
        void this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(filtersGroup).setName("Date range").addDropdown(
      (dropdown) => dropdown.addOption("upcoming", "Upcoming").addOption("week", "Next 7 days").addOption("month", "Next month").addOption("all", "All").setValue(filters.dateRange).onChange((value) => {
        filters.dateRange = value;
        this.shouldRestoreSearchFocus = true;
        this.searchCursorPosition = null;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(filtersGroup).setName("Show completed").addToggle(
      (toggle) => toggle.setValue(filters.includeCompleted).onChange((value) => {
        filters.includeCompleted = value;
        this.shouldRestoreSearchFocus = true;
        this.searchCursorPosition = null;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(filtersGroup).setName("Show archived").addToggle(
      (toggle) => toggle.setValue(filters.includeArchived).onChange((value) => {
        filters.includeArchived = value;
        this.shouldRestoreSearchFocus = true;
        this.searchCursorPosition = null;
        void this.plugin.saveSettings();
      })
    );
  }
  renderEntry(ul, entry) {
    const eventLi = ul.createEl("li", {
      cls: `memento-tl-event memento-tl-${entry.sourceType}`
    });
    eventLi.addEventListener("click", () => {
      void this.openEntryActions(entry);
    });
    const quickBtn = eventLi.createDiv({ cls: "memento-tl-delete-btn" });
    (0, import_obsidian2.setIcon)(quickBtn, entry.editable ? "trash-2" : "eye-off");
    quickBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      if (entry.editable) {
        new ConfirmModal(
          this.plugin.app,
          "Delete Event",
          "Are you sure you want to permanently delete this event?",
          () => {
            this.plugin.deleteEvent(entry.event.id);
          },
          "Delete",
          true
        ).open();
      } else {
        this.plugin.hideExternalEvent(entry.event.id);
      }
    });
    const contentDiv = eventLi.createDiv({ cls: "memento-tl-content" });
    const dateDiv = contentDiv.createDiv({ cls: "memento-tl-date" });
    dateDiv.createSpan({
      text: formatDateDisplay(entry.occurrenceDate),
      cls: "memento-tl-date-text main-date"
    });
    const metaDiv = contentDiv.createDiv({ cls: "memento-tl-time" });
    if (entry.occurrenceTime) {
      metaDiv.createSpan({
        text: formatTimeDisplay(entry.occurrenceTime),
        cls: "memento-tl-time-text"
      });
    }
    if (entry.event.recurrence !== "none") {
      metaDiv.createSpan({
        text: getRecurrenceLabel(entry.event),
        cls: "memento-tl-recurrence-badge"
      });
    }
    metaDiv.createSpan({
      text: entry.sourceName,
      cls: `memento-tl-source-badge memento-tl-source-${entry.sourceType}`
    });
    this.renderRemaining(contentDiv, entry.occurrenceDate);
    const titleDiv = contentDiv.createDiv({ cls: "memento-tl-title" });
    titleDiv.createSpan({
      text: entry.event.title,
      cls: "memento-tl-title-text"
    });
    if (entry.event.context) {
      const contextDiv = contentDiv.createDiv({ cls: "memento-tl-context" });
      contextDiv.createEl("p", { text: entry.event.context });
    }
    if (isExternalEvent(entry.event) && entry.event.location) {
      const locationDiv = contentDiv.createDiv({ cls: "memento-tl-context" });
      locationDiv.createEl("p", { text: entry.event.location });
    }
  }
  renderRemaining(container, occurrenceDate) {
    const today = /* @__PURE__ */ new Date();
    const todayStr = `${today.getFullYear()}-${(today.getMonth() + 1).toString().padStart(2, "0")}-${today.getDate().toString().padStart(2, "0")}`;
    const eventDate = /* @__PURE__ */ new Date(occurrenceDate + "T00:00:00");
    const diffTime = eventDate.getTime() - (/* @__PURE__ */ new Date(todayStr + "T00:00:00")).getTime();
    const diffDays = Math.round(diffTime / (1e3 * 60 * 60 * 24));
    let remainingText = "";
    if (diffDays === 0) {
      remainingText = "(Today)";
    } else if (diffDays === 1) {
      remainingText = "(Tomorrow)";
    } else if (diffDays > 1) {
      remainingText = `(${diffDays} days remaining)`;
    } else if (diffDays < 0) {
      remainingText = `(${-diffDays} days ago)`;
    }
    if (remainingText) {
      const remainingDiv = container.createDiv({
        cls: "memento-tl-remaining"
      });
      remainingDiv.createEl("em", { text: remainingText });
    }
  }
  async openEntryActions(entry) {
    const filePath = this.plugin.getEventNotePath(entry.event, entry.occurrenceDate);
    const fileExists = await this.plugin.app.vault.adapter.exists(filePath);
    new EventActionModal(this.plugin.app, entry, fileExists, {
      edit: () => {
        if (isMementoEvent(entry.event)) this.openEditEventModal(entry.event);
      },
      openNote: () => {
        void this.plugin.createNoteForEvent(entry.event, entry.occurrenceDate);
      },
      duplicate: () => {
        if (isMementoEvent(entry.event)) this.plugin.duplicateEvent(entry.event);
      },
      complete: () => {
        if (isMementoEvent(entry.event)) this.plugin.setEventStatus(entry.event.id, "completed");
      },
      archive: () => {
        if (isMementoEvent(entry.event)) this.plugin.setEventStatus(entry.event.id, "archived");
      },
      deleteEvent: () => {
        this.plugin.deleteEvent(entry.event.id);
      },
      importExternal: () => {
        if (isExternalEvent(entry.event))
          this.plugin.importExternalEvent(entry.event, entry.occurrenceDate);
      },
      hideExternal: () => {
        this.plugin.hideExternalEvent(entry.event.id);
      },
      copyDetails: () => {
        const lines = [
          entry.event.title,
          formatDateDisplay(entry.occurrenceDate),
          entry.occurrenceTime ? formatTimeDisplay(entry.occurrenceTime) : "",
          entry.event.context
        ].filter(Boolean);
        void navigator.clipboard.writeText(lines.join("\n"));
      }
    }).open();
  }
  renderEmptyState(container) {
    const empty = container.createDiv({ cls: "memento-empty-state" });
    const iconDiv = empty.createDiv({ cls: "memento-empty-icon" });
    (0, import_obsidian2.setIcon)(iconDiv, "calendar-days");
    empty.createEl("h3", { text: "No events found" });
    empty.createEl("p", {
      text: "Create a Memento event, adjust filters, or add an external ICS calendar in settings.",
      cls: "memento-empty-desc"
    });
  }
  openEditEventModal(event) {
    new EventModal(
      this.plugin.app,
      (updatedEvent) => {
        this.plugin.updateEvent(updatedEvent);
      },
      event
    ).open();
  }
};
function isExternalEvent(event) {
  return "externalUid" in event;
}
function isMementoEvent(event) {
  return !isExternalEvent(event);
}

// src/CalendarDecorator.ts
var import_obsidian3 = require("obsidian");
var CalendarDecorator = class {
  constructor(plugin) {
    this.observer = null;
    this.decorationTimeoutId = null;
    this.addBtnOverlay = null;
    this.currentHoverDate = null;
    this.mouseMoveHandler = this.onMouseMove.bind(this);
    this.contextMenuHandler = this.onContextMenu.bind(this);
    this.plugin = plugin;
  }
  /**
   * Start observing the workspace for Calendar plugin views
   */
  start() {
    this.createAddButtonOverlay();
    this.plugin.registerEvent(
      this.plugin.app.workspace.on("layout-change", () => {
        this.scheduleDecoration();
      })
    );
    this.setupDomObserver();
    window.addEventListener("mousemove", this.mouseMoveHandler, {
      passive: true
    });
    window.addEventListener("contextmenu", this.contextMenuHandler, true);
    this.plugin.register(() => {
      window.removeEventListener("mousemove", this.mouseMoveHandler);
      window.removeEventListener("contextmenu", this.contextMenuHandler, true);
      if (this.addBtnOverlay) {
        this.addBtnOverlay.remove();
        this.addBtnOverlay = null;
      }
    });
    this.scheduleDecoration();
  }
  /**
   * Creates a single floating add button in the document body.
   */
  createAddButtonOverlay() {
    if (this.addBtnOverlay) return;
    this.addBtnOverlay = activeDocument.createElement("div");
    this.addBtnOverlay.className = "memento-add-btn memento-floating-btn";
    this.addBtnOverlay.setText("+");
    this.addBtnOverlay.setAttribute("aria-label", "Create Event");
    this.addBtnOverlay.setCssStyles({ display: "none" });
    activeDocument.body.appendChild(this.addBtnOverlay);
    this.addBtnOverlay.addEventListener("click", (e) => {
      e.stopPropagation();
      e.preventDefault();
      if (this.currentHoverDate) {
        this.plugin.createEventForDate(this.currentHoverDate);
      }
    });
  }
  /**
   * Intercepts right clicks on calendar days globally using the capture phase.
   */
  onContextMenu(e) {
    const target = e.target;
    if (!target || !target.closest) return;
    const dayCell = target.closest(".day");
    if (dayCell && !dayCell.hasClass("adjacent-month")) {
      const leafContent = dayCell.closest(".workspace-leaf-content") || dayCell.closest(".workspace-leaf");
      if (leafContent) {
        const dateStr = this.extractDateFromCell(
          dayCell,
          leafContent
        );
        if (dateStr) {
          e.preventDefault();
          e.stopImmediatePropagation();
          const menu = new import_obsidian3.Menu();
          menu.addItem((item) => {
            item.setTitle("Create Event").setIcon("calendar-plus").onClick(() => {
              this.plugin.createEventForDate(dateStr);
            });
          });
          const eventsOnDate = this.plugin.settings.events.filter(
            (ev) => ev.date === dateStr || ev.recurrence !== "none"
          );
          if (eventsOnDate.length > 0) {
            menu.addSeparator();
            menu.addItem((item) => {
              item.setTitle("\u{1F4CB} View Events Timeline").setIcon("list").onClick(() => {
                void this.plugin.activateTimelineView();
              });
            });
          }
          menu.showAtMouseEvent(e);
        }
      }
    }
  }
  /**
   * Tracks the mouse to see if we are hovering over a calendar day cell.
   */
  onMouseMove(e) {
    const target = e.target;
    if (!target || !target.closest) return;
    if (this.addBtnOverlay && (target === this.addBtnOverlay || this.addBtnOverlay.contains(target))) {
      return;
    }
    const dayCell = target.closest(".day");
    if (dayCell && !dayCell.hasClass("adjacent-month")) {
      const leafContent = dayCell.closest(".workspace-leaf-content") || dayCell.closest(".workspace-leaf");
      if (leafContent) {
        const dateStr = this.extractDateFromCell(
          dayCell,
          leafContent
        );
        if (dateStr && this.addBtnOverlay) {
          this.currentHoverDate = dateStr;
          const rect = dayCell.getBoundingClientRect();
          this.addBtnOverlay.setCssStyles({
            display: "flex",
            top: `${rect.top + 2}px`,
            left: `${rect.left + 2}px`
          });
          return;
        }
      }
    }
    if (this.addBtnOverlay) {
      this.addBtnOverlay.setCssStyles({ display: "none" });
      this.currentHoverDate = null;
    }
  }
  /**
   * Schedule decoration with a small debounce to avoid excessive DOM manipulation
   */
  scheduleDecoration() {
    if (this.decorationTimeoutId !== null) {
      window.clearTimeout(this.decorationTimeoutId);
    }
    this.decorationTimeoutId = window.setTimeout(() => {
      this.decorateCalendar();
      this.decorationTimeoutId = null;
    }, 100);
  }
  /**
   * Set up a MutationObserver on the workspace to detect calendar DOM changes
   */
  setupDomObserver() {
    if (this.observer) {
      this.observer.disconnect();
    }
    this.observer = new MutationObserver(() => {
      this.scheduleDecoration();
    });
    const workspaceEl = activeDocument.querySelector(".workspace");
    if (workspaceEl) {
      this.observer.observe(workspaceEl, {
        childList: true,
        subtree: true,
        attributes: false,
        characterData: false
      });
    }
    this.plugin.register(() => {
      if (this.observer) {
        this.observer.disconnect();
        this.observer = null;
      }
    });
  }
  /**
   * Find the Calendar plugin view and decorate its day cells
   */
  decorateCalendar() {
    const calendarLeaves = this.plugin.app.workspace.getLeavesOfType("calendar");
    if (calendarLeaves.length === 0) return;
    const eventDates = getEventDatesSet(
      this.plugin.settings.events,
      730,
      // 2 years lookahead for calendar highlights
      this.plugin.settings.externalEventsCache,
      this.plugin.settings.externalCalendarSources,
      this.plugin.settings.hiddenExternalEventIds
    );
    for (const leaf of calendarLeaves) {
      this.decorateLeaf(leaf, eventDates);
    }
  }
  /**
   * Decorate a single calendar leaf's day cells.
   * Only sets up the border highlighting now, as the Add button is handled globally.
   */
  decorateLeaf(leaf, eventDates) {
    const container = leaf.view.containerEl;
    if (!container) return;
    const dayCells = container.querySelectorAll(".day");
    for (const cell of Array.from(dayCells)) {
      const dayEl = cell;
      const dateStr = this.extractDateFromCell(dayEl, container);
      if (!dateStr) continue;
      if (eventDates.has(dateStr)) {
        dayEl.addClass("has-memento-event");
      } else {
        dayEl.removeClass("has-memento-event");
      }
    }
  }
  /**
   * Extract the date string from a calendar day cell.
   * The calendar renders a grid, and we extract the month/year robustly from the container's text.
   */
  extractDateFromCell(cell, container) {
    const dayText = cell.textContent?.trim();
    if (!dayText) return null;
    const dayNum = parseInt(dayText, 10);
    if (isNaN(dayNum) || dayNum < 1 || dayNum > 31) return null;
    let month = (/* @__PURE__ */ new Date()).getMonth() + 1;
    let year = (/* @__PURE__ */ new Date()).getFullYear();
    const monthEl = container.querySelector(".title .month");
    const yearEl = container.querySelector(".title .year");
    if (monthEl && yearEl) {
      const mText = monthEl.textContent?.trim() || "";
      const yText = yearEl.textContent?.trim() || "";
      const parsedY = parseInt(yText, 10);
      if (!isNaN(parsedY)) {
        year = parsedY;
      }
      const mNum = this.getMonthNumber(mText);
      if (mNum > 0) {
        month = mNum;
      }
    } else {
      const containerText = container.innerText || container.textContent || "";
      const parsedMonthYear = this.parseMonthYearRobust(containerText);
      if (parsedMonthYear) {
        month = parsedMonthYear.month;
        year = parsedMonthYear.year;
      }
    }
    const isAdjacentMonth = cell.hasClass("adjacent-month") || cell.hasClass("previous-month") || cell.hasClass("next-month");
    if (isAdjacentMonth) {
      if (dayNum > 20) {
        month -= 1;
        if (month < 1) {
          month = 12;
          year -= 1;
        }
      } else {
        month += 1;
        if (month > 12) {
          month = 1;
          year += 1;
        }
      }
    }
    return `${year}-${month.toString().padStart(2, "0")}-${dayNum.toString().padStart(2, "0")}`;
  }
  getMonthNumber(monthStr) {
    if (!monthStr) return 0;
    const clean = monthStr.replace(/\./g, "").trim().toLowerCase();
    const monthNamesEn = [
      "january",
      "february",
      "march",
      "april",
      "may",
      "june",
      "july",
      "august",
      "september",
      "october",
      "november",
      "december"
    ];
    const monthNamesEs = [
      "enero",
      "febrero",
      "marzo",
      "abril",
      "mayo",
      "junio",
      "julio",
      "agosto",
      "septiembre",
      "octubre",
      "noviembre",
      "diciembre"
    ];
    const monthNamesShortEn = [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec"
    ];
    const monthNamesShortEs = [
      "ene",
      "feb",
      "mar",
      "abr",
      "may",
      "jun",
      "jul",
      "ago",
      "sep",
      "oct",
      "nov",
      "dic"
    ];
    let m = monthNamesEn.indexOf(clean) + 1;
    if (m === 0) m = monthNamesEs.indexOf(clean) + 1;
    if (m === 0) m = monthNamesShortEn.indexOf(clean) + 1;
    if (m === 0) m = monthNamesShortEs.indexOf(clean) + 1;
    if (m > 0) return m;
    if (window.moment) {
      const parsed = window.moment(clean, ["MMM", "MMMM"], true);
      if (parsed.isValid()) return parsed.month() + 1;
      const parsedLoose = window.moment(clean, ["MMM", "MMMM"]);
      if (parsedLoose.isValid()) return parsedLoose.month() + 1;
    }
    return 0;
  }
  parseMonthYearRobust(text) {
    const cleanText = text.toLowerCase().replace(/[,.]/g, " ").replace(/\s+/g, " ");
    const monthNamesEn = [
      "january",
      "february",
      "march",
      "april",
      "may",
      "june",
      "july",
      "august",
      "september",
      "october",
      "november",
      "december"
    ];
    const monthNamesEs = [
      "enero",
      "febrero",
      "marzo",
      "abril",
      "mayo",
      "junio",
      "julio",
      "agosto",
      "septiembre",
      "octubre",
      "noviembre",
      "diciembre"
    ];
    const monthNamesShortEn = [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec"
    ];
    const monthNamesShortEs = [
      "ene",
      "feb",
      "mar",
      "abr",
      "may",
      "jun",
      "jul",
      "ago",
      "sep",
      "oct",
      "nov",
      "dic"
    ];
    const allMonths = [
      ...monthNamesEn,
      ...monthNamesEs,
      ...monthNamesShortEn,
      ...monthNamesShortEs
    ];
    for (const m of allMonths) {
      const regex1 = new RegExp(`\\b${m}\\s+(?:de\\s+)?(20\\d\\d)\\b`);
      const match1 = cleanText.match(regex1);
      if (match1)
        return { month: this.getMonthNumber(m), year: parseInt(match1[1], 10) };
      const regex2 = new RegExp(`\\b(20\\d\\d)\\s+(?:de\\s+)?${m}\\b`);
      const match2 = cleanText.match(regex2);
      if (match2)
        return { month: this.getMonthNumber(m), year: parseInt(match2[1], 10) };
    }
    const numMatch1 = cleanText.match(/\b(20\d\d)[-/ ](\d{1,2})\b/);
    if (numMatch1) {
      const m = parseInt(numMatch1[2], 10);
      if (m >= 1 && m <= 12)
        return { month: m, year: parseInt(numMatch1[1], 10) };
    }
    const numMatch2 = cleanText.match(/\b(\d{1,2})[-/ ](20\d\d)\b/);
    if (numMatch2) {
      const m = parseInt(numMatch2[1], 10);
      if (m >= 1 && m <= 12)
        return { month: m, year: parseInt(numMatch2[2], 10) };
    }
    return null;
  }
  /**
   * Handle right-click on a day cell
   */
  onDayContextMenu(e, dateStr) {
    const menu = new import_obsidian3.Menu();
    menu.addItem((item) => {
      item.setTitle("Create Event").setIcon("calendar-plus").onClick(() => {
        this.plugin.createEventForDate(dateStr);
      });
    });
    const eventsOnDate = this.plugin.settings.events.filter(
      (ev) => ev.date === dateStr || ev.recurrence !== "none"
    );
    if (eventsOnDate.length > 0) {
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("\u{1F4CB} View Events").setIcon("list").onClick(() => {
          void this.plugin.activateTimelineView();
        });
      });
    }
    menu.showAtMouseEvent(e);
  }
  /**
   * Force refresh decorations (called after event changes)
   */
  refresh() {
    this.scheduleDecoration();
  }
  /**
   * Clean up
   */
  destroy() {
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }
    if (this.decorationTimeoutId !== null) {
      window.clearTimeout(this.decorationTimeoutId);
    }
    const cells = activeDocument.querySelectorAll(".has-memento-event");
    cells.forEach((cell) => cell.removeClass("has-memento-event"));
  }
};

// src/EventSettingsTab.ts
var import_obsidian4 = require("obsidian");
var EventSettingsTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    this.render();
  }
  render() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("memento-settings");
    this.renderTimelineSettings(containerEl);
    this.renderExternalCalendars(containerEl);
    this.renderDataManagement(containerEl);
    this.renderEvents(containerEl);
  }
  renderTimelineSettings(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Timeline").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Timeline view mode").setDesc("Choose which events to show in the timeline view").addDropdown(
      (dropdown) => dropdown.addOption("all", "Show all upcoming events").addOption("month", "Show events for current month only").setValue(this.plugin.settings.timelineViewMode).onChange(async (value) => {
        this.plugin.settings.timelineViewMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show past events").setDesc("Display expired one-time events in the list below").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showPastEventsInSettings).onChange(async (value) => {
        this.plugin.settings.showPastEventsInSettings = value;
        void this.plugin.saveSettings().then(() => this.render());
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Frontmatter language").setDesc("Language for the properties when creating a note from an event").addDropdown(
      (dropdown) => dropdown.addOption("en", "English (Title, Date, Context)").addOption("es", "Spanish (T\xEDtulo, Fecha, Contexto)").setValue(this.plugin.settings.frontmatterLanguage).onChange(async (value) => {
        this.plugin.settings.frontmatterLanguage = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Event notes folder").setDesc(
      "Folder where event notes will be created. Leave empty for vault root."
    ).addText(
      (text) => text.setPlaceholder("e.g. Calendar/Events").setValue(this.plugin.settings.eventNoteFolder).onChange(async (value) => {
        this.plugin.settings.eventNoteFolder = value;
        await this.plugin.saveSettings();
      })
    );
  }
  renderExternalCalendars(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("External Calendars").setHeading();
    let name = "";
    let url = "";
    let refreshIntervalMinutes = 60;
    new import_obsidian4.Setting(containerEl).setName("Add ICS calendar").setDesc("Use a private Google Calendar ICS URL or shared iCloud ICS URL").addText(
      (text) => text.setPlaceholder("Calendar name").onChange((value) => {
        name = value.trim();
      })
    ).addText(
      (text) => text.setPlaceholder("https://...ics").onChange((value) => {
        url = value.trim();
      })
    ).addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "5";
      text.setPlaceholder("Refresh minutes");
      text.setValue(refreshIntervalMinutes.toString());
      text.onChange((value) => {
        const parsed = parseInt(value, 10);
        refreshIntervalMinutes = Number.isNaN(parsed) ? 60 : Math.max(5, parsed);
      });
    }).addButton(
      (button) => button.setButtonText("Add").setCta().onClick(() => {
        if (!name || !url) {
          new import_obsidian4.Notice("Calendar name and ICS URL are required.");
          return;
        }
        this.plugin.addExternalCalendarSource({
          name,
          type: "ics",
          url,
          enabled: true,
          refreshIntervalMinutes
        });
        this.render();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Refresh external calendars").setDesc("Fetch all enabled ICS subscriptions now").addButton(
      (button) => button.setButtonText("Refresh now").onClick(() => {
        void this.plugin.syncExternalCalendars().then(() => this.render());
      })
    );
    for (const source of this.plugin.settings.externalCalendarSources) {
      this.renderExternalCalendarItem(containerEl, source);
    }
  }
  renderExternalCalendarItem(containerEl, source) {
    const sourceEvents = this.plugin.settings.externalEventsCache.filter(
      (event) => event.sourceId === source.id
    );
    new import_obsidian4.Setting(containerEl).setName(source.name).setDesc(
      `${sourceEvents.length} cached events${source.lastFetchedAt ? ` \xB7 Last sync ${source.lastFetchedAt}` : ""}${source.lastError ? ` \xB7 Error: ${source.lastError}` : ""}`
    ).addToggle(
      (toggle) => toggle.setValue(source.enabled).onChange((value) => {
        this.plugin.updateExternalCalendarSource({ ...source, enabled: value });
        this.render();
      })
    ).addButton(
      (button) => button.setButtonText("Refresh").onClick(() => {
        void this.plugin.syncExternalCalendars([source.id]).then(() => this.render());
      })
    ).addButton(
      (button) => button.setButtonText("Remove").setWarning().onClick(() => {
        this.plugin.deleteExternalCalendarSource(source.id);
        this.render();
      })
    );
  }
  renderDataManagement(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Data Management").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Export events").setDesc("Create a JSON backup file in the vault root").addButton(
      (button) => button.setButtonText("Export JSON").onClick(() => {
        void this.plugin.exportEventsToJson();
      })
    );
    let importText = "";
    new import_obsidian4.Setting(containerEl).setName("Import events").setDesc("Paste a Memento JSON export. Duplicate ids are regenerated.").addTextArea(
      (text) => text.setPlaceholder("Paste JSON").onChange((value) => {
        importText = value;
      })
    ).addButton(
      (button) => button.setButtonText("Import JSON").onClick(() => {
        try {
          const count = this.plugin.importEventsFromJson(importText);
          new import_obsidian4.Notice(`Imported ${count} events.`);
          this.render();
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          new import_obsidian4.Notice(`Import failed: ${message}`);
        }
      })
    );
  }
  renderEvents(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Events").setHeading().settingEl.addClass("memento-settings-events-heading");
    new import_obsidian4.Setting(containerEl).setName("Create a new event").setDesc("Add a new event to your calendar").addButton(
      (button) => button.setButtonText("+ Add Event").setCta().onClick(() => {
        new EventModal(this.app, (event) => {
          this.plugin.settings.events.push({
            ...event,
            id: event.id || generateId(),
            updatedAt: (/* @__PURE__ */ new Date()).toISOString()
          });
          void this.plugin.saveSettings().then(() => this.render());
        }).open();
      })
    );
    const events = this.getFilteredEvents();
    if (events.length === 0) {
      const emptyDiv = containerEl.createDiv({ cls: "memento-settings-empty" });
      emptyDiv.createEl("p", {
        text: "No events yet. Create your first event above.",
        cls: "setting-item-description"
      });
    } else {
      const eventsContainer = containerEl.createDiv({
        cls: "memento-settings-events"
      });
      for (const event of events) {
        this.renderEventItem(eventsContainer, event);
      }
    }
  }
  getFilteredEvents() {
    let events = [...this.plugin.settings.events];
    if (!this.plugin.settings.showPastEventsInSettings) {
      const todayStr = getTodayStr();
      events = events.filter((event) => {
        if (event.status === "archived") return false;
        if (event.recurrence !== "none") return true;
        return event.date >= todayStr;
      });
    }
    events.sort((a, b) => a.date.localeCompare(b.date));
    return events;
  }
  renderEventItem(container, event) {
    const eventEl = container.createDiv({ cls: "memento-settings-event" });
    const infoEl = eventEl.createDiv({ cls: "memento-settings-event-info" });
    const titleRow = infoEl.createDiv({
      cls: "memento-settings-event-title-row"
    });
    titleRow.createSpan({
      text: event.title,
      cls: "memento-settings-event-title"
    });
    titleRow.createSpan({
      text: event.status || "active",
      cls: "memento-settings-event-badge"
    });
    if (event.recurrence !== "none") {
      titleRow.createSpan({
        text: getRecurrenceLabel(event),
        cls: "memento-settings-event-badge"
      });
    }
    const metaRow = infoEl.createDiv({ cls: "memento-settings-event-meta" });
    metaRow.createSpan({
      text: formatDateDisplay(event.date),
      cls: "memento-settings-event-date"
    });
    if (event.time) {
      metaRow.createSpan({ text: " \xB7 " });
      metaRow.createSpan({
        text: formatTimeDisplay(event.time),
        cls: "memento-settings-event-time"
      });
    }
    if (event.context) {
      infoEl.createEl("p", {
        text: event.context,
        cls: "memento-settings-event-context"
      });
    }
    const actionsEl = eventEl.createDiv({
      cls: "memento-settings-event-actions"
    });
    this.addIconButton(actionsEl, "pencil", "Edit event", () => {
      new EventModal(
        this.app,
        (updatedEvent) => {
          this.plugin.updateEvent(updatedEvent);
          this.render();
        },
        event
      ).open();
    });
    this.addIconButton(actionsEl, "copy", "Duplicate event", () => {
      this.plugin.duplicateEvent(event);
      this.render();
    });
    this.addIconButton(actionsEl, "check", "Mark complete", () => {
      this.plugin.setEventStatus(event.id, "completed");
      this.render();
    });
    this.addIconButton(actionsEl, "archive", "Archive event", () => {
      this.plugin.setEventStatus(event.id, "archived");
      this.render();
    });
    this.addIconButton(actionsEl, "trash-2", "Delete event", () => {
      this.plugin.deleteEvent(event.id);
      this.render();
    }).addClass("memento-settings-btn-delete");
  }
  addIconButton(container, icon, label, onClick) {
    const button = container.createEl("button", {
      cls: "memento-settings-btn",
      attr: { "aria-label": label }
    });
    (0, import_obsidian4.setIcon)(button, icon);
    button.addEventListener("click", onClick);
    return button;
  }
};

// src/IcsSync.ts
var import_obsidian5 = require("obsidian");
async function syncExternalCalendarSource(source, existingEvents) {
  const response = await (0, import_obsidian5.requestUrl)({ url: source.url });
  const seenAt = (/* @__PURE__ */ new Date()).toISOString();
  const existingByUid = new Map(
    existingEvents.filter((event) => event.sourceId === source.id).map((event) => [event.externalUid, event])
  );
  const parsed = parseIcs(response.text, source.id, seenAt, existingByUid);
  return {
    source: {
      ...source,
      lastFetchedAt: seenAt,
      lastError: ""
    },
    events: parsed
  };
}
function parseIcs(icsText, sourceId, seenAt, existingByUid = /* @__PURE__ */ new Map()) {
  const lines = unfoldIcsLines(icsText);
  const rawEvents = [];
  let current = null;
  for (const line of lines) {
    if (line === "BEGIN:VEVENT") {
      current = {};
      continue;
    }
    if (line === "END:VEVENT") {
      if (current?.dtstart) {
        rawEvents.push({
          uid: current.uid || generateId(),
          summary: current.summary || "Untitled event",
          description: current.description || "",
          location: current.location || "",
          url: current.url || "",
          dtstart: current.dtstart,
          dtend: current.dtend || "",
          rrule: current.rrule || ""
        });
      }
      current = null;
      continue;
    }
    if (!current) continue;
    const { name, value } = parseProperty(line);
    switch (name) {
      case "UID":
        current.uid = value;
        break;
      case "SUMMARY":
        current.summary = decodeIcsText(value);
        break;
      case "DESCRIPTION":
        current.description = decodeIcsText(value);
        break;
      case "LOCATION":
        current.location = decodeIcsText(value);
        break;
      case "URL":
        current.url = decodeIcsText(value);
        break;
      case "DTSTART":
        current.dtstart = value;
        break;
      case "DTEND":
        current.dtend = value;
        break;
      case "RRULE":
        current.rrule = value;
        break;
      default:
        break;
    }
  }
  return rawEvents.map((event) => normalizeIcsEvent(event, sourceId, seenAt, existingByUid));
}
function normalizeIcsEvent(event, sourceId, seenAt, existingByUid) {
  const start = parseIcsDate(event.dtstart);
  const end = event.dtend ? parseIcsDate(event.dtend) : null;
  const recurrence = parseRrule(event.rrule);
  const existing = existingByUid.get(event.uid);
  return {
    id: existing?.id || generateId(),
    sourceId,
    externalUid: event.uid,
    title: event.summary,
    context: event.description,
    location: event.location,
    url: event.url,
    date: start.date,
    time: start.time,
    endDate: end?.date,
    endTime: end?.time,
    allDay: start.allDay,
    recurrence: recurrence.recurrence,
    recurrenceInterval: recurrence.recurrenceInterval,
    recurrenceEndDate: recurrence.recurrenceEndDate,
    recurrenceCount: recurrence.recurrenceCount,
    notePaths: existing?.notePaths || {},
    lastSeenAt: seenAt
  };
}
function unfoldIcsLines(text) {
  const rawLines = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
  const lines = [];
  for (const rawLine of rawLines) {
    if (/^[ \t]/.test(rawLine) && lines.length > 0) {
      lines[lines.length - 1] += rawLine.slice(1);
    } else {
      lines.push(rawLine.trimEnd());
    }
  }
  return lines;
}
function parseProperty(line) {
  const colonIdx = line.indexOf(":");
  if (colonIdx === -1) return { name: line, value: "" };
  const rawName = line.slice(0, colonIdx);
  const name = rawName.split(";")[0].toUpperCase();
  return { name, value: line.slice(colonIdx + 1) };
}
function decodeIcsText(value) {
  return value.replace(/\\n/gi, "\n").replace(/\\,/g, ",").replace(/\\;/g, ";").replace(/\\\\/g, "\\").trim();
}
function parseIcsDate(value) {
  const clean = value.trim();
  if (/^\d{8}$/.test(clean)) {
    return {
      date: `${clean.slice(0, 4)}-${clean.slice(4, 6)}-${clean.slice(6, 8)}`,
      time: "",
      allDay: true
    };
  }
  const match = clean.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})/);
  if (!match) {
    return { date: dateToStr(/* @__PURE__ */ new Date()), time: "", allDay: true };
  }
  if (clean.endsWith("Z")) {
    const date = /* @__PURE__ */ new Date(
      `${match[1]}-${match[2]}-${match[3]}T${match[4]}:${match[5]}:00Z`
    );
    return {
      date: dateToStr(date),
      time: `${date.getHours().toString().padStart(2, "0")}:${date.getMinutes().toString().padStart(2, "0")}`,
      allDay: false
    };
  }
  return {
    date: `${match[1]}-${match[2]}-${match[3]}`,
    time: `${match[4]}:${match[5]}`,
    allDay: false
  };
}
function parseRrule(rrule) {
  if (!rrule) return { recurrence: "none" };
  const parts = Object.fromEntries(
    rrule.split(";").map((part) => {
      const [key, value] = part.split("=");
      return [key?.toUpperCase() || "", value || ""];
    })
  );
  const freq = parts.FREQ?.toUpperCase();
  const recurrence = frequencyToRecurrence(freq);
  const interval = parseInt(parts.INTERVAL || "1", 10);
  const count = parseInt(parts.COUNT || "", 10);
  return {
    recurrence,
    recurrenceInterval: Number.isNaN(interval) ? 1 : Math.max(1, interval),
    recurrenceEndDate: parts.UNTIL ? parseIcsDate(parts.UNTIL).date : void 0,
    recurrenceCount: Number.isNaN(count) ? void 0 : count
  };
}
function frequencyToRecurrence(freq) {
  switch (freq) {
    case "DAILY":
      return "daily";
    case "WEEKLY":
      return "weekly";
    case "MONTHLY":
      return "monthly";
    case "YEARLY":
      return "yearly";
    default:
      return "none";
  }
}

// src/main.ts
var MementoPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_TIMELINE, (leaf) => {
      return new TimelineView(leaf, this);
    });
    this.addSettingTab(new EventSettingsTab(this.app, this));
    this.decorator = new CalendarDecorator(this);
    this.addCommand({
      id: "create-event",
      name: "Create a new event",
      callback: () => {
        this.openCreateEventModal();
      }
    });
    this.addCommand({
      id: "create-event-today",
      name: "Create event for today",
      callback: () => {
        this.createEventForDate(getTodayStr());
      }
    });
    this.addCommand({
      id: "open-timeline",
      name: "Open event timeline",
      callback: () => {
        void this.activateTimelineView();
      }
    });
    this.addCommand({
      id: "refresh-external-calendars",
      name: "Refresh external calendars",
      callback: () => {
        void this.syncExternalCalendars();
      }
    });
    this.addRibbonIcon("calendar-clock", "Memento \u2014 Event Timeline", () => {
      void this.activateTimelineView();
    });
    this.app.workspace.onLayoutReady(() => {
      this.decorator.start();
      void this.activateTimelineView();
      void this.syncDueExternalCalendars();
    });
    this.registerInterval(
      window.setInterval(() => {
        this.refreshTimeline();
        this.decorator.refresh();
        void this.syncDueExternalCalendars();
      }, 60 * 1e3)
    );
  }
  onunload() {
    if (this.decorator) {
      this.decorator.destroy();
    }
    this.app.workspace.getLeavesOfType(VIEW_TYPE_TIMELINE).forEach((leaf) => {
      leaf.detach();
    });
  }
  // ─── Settings Persistence ────────────────────────────────────────
  async loadSettings() {
    const data = await this.loadData() || {};
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...data,
      timelineFilters: {
        ...DEFAULT_TIMELINE_FILTERS,
        ...data.timelineFilters || {}
      },
      externalCalendarSources: data.externalCalendarSources || [],
      externalEventsCache: data.externalEventsCache || [],
      hiddenExternalEventIds: data.hiddenExternalEventIds || [],
      events: (data.events || []).map((event) => normalizeEvent(event))
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshTimeline();
    this.decorator?.refresh();
  }
  // ─── Event Management ────────────────────────────────────────────
  openCreateEventModal() {
    new EventModal(this.app, (event) => {
      this.settings.events.push(this.prepareEvent(event));
      void this.saveSettings();
    }).open();
  }
  createEventForDate(dateStr) {
    new EventModal(
      this.app,
      (event) => {
        this.settings.events.push(this.prepareEvent(event));
        void this.saveSettings();
      },
      void 0,
      dateStr
    ).open();
  }
  updateEvent(updatedEvent) {
    const idx = this.settings.events.findIndex((event) => event.id === updatedEvent.id);
    if (idx === -1) return;
    this.settings.events[idx] = this.prepareEvent({
      ...this.settings.events[idx],
      ...updatedEvent,
      updatedAt: (/* @__PURE__ */ new Date()).toISOString()
    });
    void this.saveSettings();
  }
  duplicateEvent(event) {
    const now = (/* @__PURE__ */ new Date()).toISOString();
    this.settings.events.push(
      this.prepareEvent({
        ...event,
        id: generateId(),
        title: `${event.title} copy`,
        status: "active",
        notePaths: {},
        createdAt: now,
        updatedAt: now
      })
    );
    void this.saveSettings();
  }
  setEventStatus(eventId, status) {
    const event = this.settings.events.find((item) => item.id === eventId);
    if (!event) return;
    event.status = status;
    event.updatedAt = (/* @__PURE__ */ new Date()).toISOString();
    void this.saveSettings();
  }
  deleteEvent(eventId) {
    this.settings.events = this.settings.events.filter((event) => event.id !== eventId);
    void this.saveSettings();
  }
  importExternalEvent(event, occurrenceDate = event.date) {
    const now = (/* @__PURE__ */ new Date()).toISOString();
    const imported = this.prepareEvent({
      id: generateId(),
      date: occurrenceDate,
      time: event.time,
      endDate: event.endDate,
      endTime: event.endTime,
      title: event.title,
      context: event.context || event.location || "",
      recurrence: event.recurrence,
      recurrenceInterval: event.recurrenceInterval,
      recurrenceEndDate: event.recurrenceEndDate,
      recurrenceCount: event.recurrenceCount,
      status: "active",
      notePaths: {},
      createdAt: now,
      updatedAt: now
    });
    this.settings.events.push(imported);
    void this.saveSettings();
    return imported;
  }
  hideExternalEvent(eventId) {
    if (!this.settings.hiddenExternalEventIds.includes(eventId)) {
      this.settings.hiddenExternalEventIds.push(eventId);
      void this.saveSettings();
    }
  }
  prepareEvent(event) {
    const now = (/* @__PURE__ */ new Date()).toISOString();
    return normalizeEvent({
      ...event,
      createdAt: event.createdAt || now,
      updatedAt: event.updatedAt || now
    });
  }
  // ─── Notes ───────────────────────────────────────────────────────
  getEventNotePath(event, occurrenceDate) {
    const existingPath = event.notePaths?.[occurrenceDate];
    if (existingPath) return existingPath;
    const folderPath = this.settings.eventNoteFolder.trim();
    const safeTitle = event.title.replace(/[\\/:"*?<>|#^[\]]/g, "").trim();
    const filename = `${occurrenceDate} - ${safeTitle || "Untitled event"}.md`;
    return folderPath ? `${folderPath}/${filename}` : filename;
  }
  async createNoteForEvent(event, occurrenceDate) {
    const { vault, workspace } = this.app;
    const folderPath = this.settings.eventNoteFolder.trim();
    if (folderPath !== "") {
      const folderExists = await vault.adapter.exists(folderPath);
      if (!folderExists) {
        await vault.createFolder(folderPath);
      }
    }
    const filePath = this.getEventNotePath(event, occurrenceDate);
    const abstractFile = vault.getAbstractFileByPath(filePath);
    let file = abstractFile instanceof import_obsidian6.TFile ? abstractFile : null;
    if (!file) {
      file = await vault.create(filePath, this.buildNoteContent(event, occurrenceDate));
      this.rememberNotePath(event, occurrenceDate, file.path);
      await this.saveSettings();
    } else {
      this.rememberNotePath(event, occurrenceDate, file.path);
      await this.syncNoteFrontmatter(file, event, occurrenceDate);
      await this.saveSettings();
    }
    const leaf = workspace.getLeaf(false);
    await leaf.openFile(file);
  }
  buildNoteContent(event, occurrenceDate) {
    const isEs = this.settings.frontmatterLanguage === "es";
    const titleKey = isEs ? "T\xEDtulo" : "Title";
    const dateKey = isEs ? "Fecha" : "Date";
    const contextKey = isEs ? "Contexto" : "Context";
    const sourceKey = isEs ? "Fuente" : "Source";
    const locationKey = isEs ? "Ubicaci\xF3n" : "Location";
    const dateTimeStr = event.time ? `${occurrenceDate} ${event.time}` : occurrenceDate;
    const source = "sourceId" in event ? "External calendar" : "Memento";
    const location = "location" in event ? event.location || "" : "";
    let content = "---\n";
    content += `${titleKey}: "${escapeYaml(event.title)}"
`;
    content += `${dateKey}: ${dateTimeStr}
`;
    content += `${contextKey}: "${escapeYaml(event.context || "")}"
`;
    content += `${sourceKey}: "${source}"
`;
    if (location) {
      content += `${locationKey}: "${escapeYaml(location)}"
`;
    }
    content += "---\n\n";
    content += `# ${event.title}
`;
    if (event.context) {
      content += `
${event.context}
`;
    }
    return content;
  }
  async syncNoteFrontmatter(file, event, occurrenceDate) {
    const dateTimeStr = event.time ? `${occurrenceDate} ${event.time}` : occurrenceDate;
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      frontmatter.Title = event.title;
      frontmatter.Date = dateTimeStr;
      frontmatter.Context = event.context || "";
      frontmatter.Source = "sourceId" in event ? "External calendar" : "Memento";
      if ("location" in event && event.location) {
        frontmatter.Location = event.location;
      }
    });
  }
  rememberNotePath(event, occurrenceDate, notePath) {
    if ("externalUid" in event) {
      const cached = this.settings.externalEventsCache.find((item) => item.id === event.id);
      if (cached) {
        cached.notePaths = { ...cached.notePaths || {}, [occurrenceDate]: notePath };
      }
      return;
    }
    const stored = this.settings.events.find((item) => item.id === event.id);
    if (stored) {
      stored.notePaths = { ...stored.notePaths || {}, [occurrenceDate]: notePath };
      stored.updatedAt = (/* @__PURE__ */ new Date()).toISOString();
    }
  }
  // ─── External Calendar Sync ──────────────────────────────────────
  addExternalCalendarSource(source) {
    this.settings.externalCalendarSources.push({
      ...source,
      id: generateId()
    });
    void this.saveSettings().then(() => this.syncExternalCalendars());
  }
  updateExternalCalendarSource(source) {
    const idx = this.settings.externalCalendarSources.findIndex(
      (item) => item.id === source.id
    );
    if (idx === -1) return;
    this.settings.externalCalendarSources[idx] = source;
    void this.saveSettings();
  }
  deleteExternalCalendarSource(sourceId) {
    this.settings.externalCalendarSources = this.settings.externalCalendarSources.filter(
      (source) => source.id !== sourceId
    );
    this.settings.externalEventsCache = this.settings.externalEventsCache.filter(
      (event) => event.sourceId !== sourceId
    );
    void this.saveSettings();
  }
  async syncDueExternalCalendars() {
    const now = Date.now();
    const dueSources = this.settings.externalCalendarSources.filter((source) => {
      if (!source.enabled) return false;
      if (!source.lastFetchedAt) return true;
      const elapsedMinutes = (now - new Date(source.lastFetchedAt).getTime()) / 6e4;
      return elapsedMinutes >= source.refreshIntervalMinutes;
    });
    if (dueSources.length === 0) return;
    await this.syncExternalCalendars(dueSources.map((source) => source.id));
  }
  async syncExternalCalendars(sourceIds) {
    const sources = this.settings.externalCalendarSources.filter((source) => {
      if (!source.enabled) return false;
      return !sourceIds || sourceIds.includes(source.id);
    });
    for (const source of sources) {
      try {
        const result = await syncExternalCalendarSource(
          source,
          this.settings.externalEventsCache
        );
        this.settings.externalCalendarSources = this.settings.externalCalendarSources.map(
          (item) => item.id === source.id ? result.source : item
        );
        this.settings.externalEventsCache = [
          ...this.settings.externalEventsCache.filter(
            (event) => event.sourceId !== source.id
          ),
          ...result.events
        ];
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        this.settings.externalCalendarSources = this.settings.externalCalendarSources.map(
          (item) => item.id === source.id ? { ...item, lastError: message, lastFetchedAt: (/* @__PURE__ */ new Date()).toISOString() } : item
        );
        new import_obsidian6.Notice(`Memento calendar sync failed: ${source.name}`);
      }
    }
    await this.saveSettings();
  }
  // ─── Data Import / Export ────────────────────────────────────────
  async exportEventsToJson() {
    const stamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
    const filename = `memento-export-${stamp}.json`;
    const payload = JSON.stringify(
      {
        version: "1.0.4",
        exportedAt: (/* @__PURE__ */ new Date()).toISOString(),
        events: this.settings.events,
        externalCalendarSources: this.settings.externalCalendarSources
      },
      null,
      2
    );
    await this.app.vault.create(filename, payload);
    new import_obsidian6.Notice(`Memento export created: ${filename}`);
  }
  importEventsFromJson(text) {
    const parsed = JSON.parse(text);
    const incoming = parsed.events || [];
    const existingIds = new Set(this.settings.events.map((event) => event.id));
    const imported = incoming.map((event) => {
      const id = existingIds.has(event.id) ? generateId() : event.id || generateId();
      existingIds.add(id);
      return this.prepareEvent({ ...event, id });
    });
    this.settings.events.push(...imported);
    void this.saveSettings();
    return imported.length;
  }
  // ─── Timeline View ───────────────────────────────────────────────
  async activateTimelineView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_TIMELINE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({
          type: VIEW_TYPE_TIMELINE,
          active: true
        });
        leaf = rightLeaf;
      }
    }
    if (leaf) {
      void workspace.revealLeaf(leaf);
    }
  }
  refreshTimeline() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TIMELINE);
    for (const leaf of leaves) {
      if (leaf.view instanceof TimelineView) {
        leaf.view.render();
      }
    }
  }
};
function escapeYaml(value) {
  return value.replace(/"/g, '\\"').replace(/\n/g, "\\n");
}
