/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MementoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  events: [],
  timelineViewMode: "all",
  showPastEventsInSettings: false,
  eventNoteFolder: "",
  frontmatterLanguage: "en"
};
var VIEW_TYPE_TIMELINE = "memento-timeline";
var RECURRENCE_LABELS = {
  none: "One-time",
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
  yearly: "Yearly"
};
function generateId() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === "x" ? r : r & 3 | 8;
    return v.toString(16);
  });
}
function formatDateDisplay(dateStr) {
  const date = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
  const mainDate = date.toLocaleDateString(void 0, {
    year: "numeric",
    month: "long",
    day: "numeric"
  });
  const weekday = date.toLocaleDateString(void 0, {
    weekday: "long"
  });
  return `${mainDate} (${weekday})`;
}
function formatTimeDisplay(time) {
  if (!time) return "";
  const [h, m] = time.split(":").map(Number);
  if (h === void 0 || m === void 0) return time;
  const ampm = h >= 12 ? "PM" : "AM";
  const hour12 = h % 12 || 12;
  return `${hour12}:${m.toString().padStart(2, "0")} ${ampm}`;
}
function getTodayStr() {
  const d = /* @__PURE__ */ new Date();
  return `${d.getFullYear()}-${(d.getMonth() + 1).toString().padStart(2, "0")}-${d.getDate().toString().padStart(2, "0")}`;
}
function getRecurrenceOccurrences(event, startRange, endRange) {
  if (event.recurrence === "none") {
    if (event.date >= startRange && event.date <= endRange) {
      return [event.date];
    }
    return [];
  }
  const occurrences = [];
  const eventDate = /* @__PURE__ */ new Date(event.date + "T00:00:00");
  const rangeStart = /* @__PURE__ */ new Date(startRange + "T00:00:00");
  const rangeEnd = /* @__PURE__ */ new Date(endRange + "T00:00:00");
  let current = new Date(eventDate);
  while (current < rangeStart) {
    current = advanceDate(current, event.recurrence, eventDate);
  }
  const maxIterations = 366;
  let iterations = 0;
  while (current <= rangeEnd && iterations < maxIterations) {
    const dateStr = dateToStr(current);
    occurrences.push(dateStr);
    current = advanceDate(current, event.recurrence, eventDate);
    iterations++;
  }
  return occurrences;
}
function advanceDate(current, recurrence, originalDate) {
  const next = new Date(current);
  switch (recurrence) {
    case "daily":
      next.setDate(next.getDate() + 1);
      break;
    case "weekly":
      next.setDate(next.getDate() + 7);
      break;
    case "monthly": {
      const origDay = originalDate.getDate();
      next.setMonth(next.getMonth() + 1);
      if (next.getDate() !== origDay) {
        next.setDate(0);
      }
      break;
    }
    case "yearly": {
      next.setFullYear(next.getFullYear() + 1);
      const origDay2 = originalDate.getDate();
      if (next.getDate() !== origDay2) {
        next.setDate(0);
      }
      break;
    }
    default:
      next.setFullYear(next.getFullYear() + 100);
      break;
  }
  return next;
}
function dateToStr(d) {
  return `${d.getFullYear()}-${(d.getMonth() + 1).toString().padStart(2, "0")}-${d.getDate().toString().padStart(2, "0")}`;
}
function getTimelineEntries(events, viewMode) {
  const today = getTodayStr();
  let startDateStr = today;
  let endDateStr;
  if (viewMode === "month") {
    const d = /* @__PURE__ */ new Date();
    d.setDate(1);
    const monthStartStr = dateToStr(d);
    startDateStr = today > monthStartStr ? today : monthStartStr;
    d.setMonth(d.getMonth() + 1);
    d.setDate(0);
    endDateStr = dateToStr(d);
  } else {
    const d = /* @__PURE__ */ new Date();
    d.setFullYear(d.getFullYear() + 2);
    endDateStr = dateToStr(d);
  }
  const entries = [];
  for (const event of events) {
    if (event.recurrence === "none") {
      if (event.date >= startDateStr && (viewMode === "all" || event.date <= endDateStr)) {
        entries.push({ event, occurrenceDate: event.date });
      }
    } else {
      const occurrences = getRecurrenceOccurrences(
        event,
        startDateStr,
        endDateStr
      );
      for (const date of occurrences) {
        entries.push({ event, occurrenceDate: date });
      }
    }
  }
  entries.sort((a, b) => {
    const dateCmp = a.occurrenceDate.localeCompare(b.occurrenceDate);
    if (dateCmp !== 0) return dateCmp;
    return a.event.time.localeCompare(b.event.time);
  });
  return entries;
}
function getEventDatesSet(events, lookaheadDays) {
  const endDate = /* @__PURE__ */ new Date();
  endDate.setDate(endDate.getDate() + lookaheadDays);
  const endStr = dateToStr(endDate);
  const startDate = /* @__PURE__ */ new Date();
  startDate.setDate(1);
  startDate.setMonth(startDate.getMonth() - 1);
  const startStr = dateToStr(startDate);
  const dates = /* @__PURE__ */ new Set();
  for (const event of events) {
    const occurrences = getRecurrenceOccurrences(event, startStr, endStr);
    for (const date of occurrences) {
      dates.add(date);
    }
  }
  return dates;
}

// src/EventModal.ts
var import_obsidian = require("obsidian");
var EventModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit, existingEvent, prefilledDate) {
    super(app);
    this.onSubmit = onSubmit;
    this.isEditing = !!existingEvent;
    if (existingEvent) {
      this.event = { ...existingEvent };
    } else {
      this.event = {
        id: generateId(),
        date: prefilledDate || getTodayStr(),
        time: "",
        title: "",
        context: "",
        recurrence: "none",
        createdAt: (/* @__PURE__ */ new Date()).toISOString()
      };
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("memento-modal");
    const header = contentEl.createDiv({ cls: "memento-modal-header" });
    header.createEl("h2", {
      text: this.isEditing ? "Edit Event" : "Create Event",
      cls: "memento-modal-title"
    });
    const dateBadge = header.createDiv({ cls: "memento-date-badge" });
    const updateDateBadge = () => {
      dateBadge.empty();
      dateBadge.createSpan({
        text: formatDateDisplay(this.event.date || getTodayStr()),
        cls: "memento-date-badge-text"
      });
    };
    updateDateBadge();
    const form = contentEl.createDiv({ cls: "memento-form" });
    new import_obsidian.Setting(form).setName("Date").setDesc("When does this event occur?").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.event.date || getTodayStr());
      text.onChange((value) => {
        this.event.date = value;
        updateDateBadge();
      });
      text.inputEl.addClass("memento-date-input");
    });
    let currentHour = "--";
    let currentMin = "--";
    if (this.event.time) {
      const [h, m] = this.event.time.split(":");
      currentHour = h;
      currentMin = m;
    }
    const timeSetting = new import_obsidian.Setting(form).setName("Time").setDesc("What time? (optional)");
    timeSetting.addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "23";
      text.inputEl.placeholder = "HH";
      text.inputEl.setCssStyles({ width: "4rem", textAlign: "center" });
      text.setValue(currentHour !== "--" ? currentHour : "");
      text.onChange((value) => {
        let val = parseInt(value, 10);
        if (isNaN(val)) {
          currentHour = "--";
        } else {
          if (val < 0) val = 0;
          if (val > 23) val = 23;
          currentHour = val.toString().padStart(2, "0");
          text.setValue(currentHour);
        }
        updateTime();
      });
    });
    const separator = timeSetting.controlEl.createSpan({
      text: " : ",
      cls: "memento-time-separator"
    });
    separator.setCssStyles({ margin: "0 0.2rem", fontWeight: "bold" });
    timeSetting.addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "59";
      text.inputEl.placeholder = "MM";
      text.inputEl.setCssStyles({ width: "4rem", textAlign: "center" });
      text.setValue(currentMin !== "--" ? currentMin : "");
      text.onChange((value) => {
        let val = parseInt(value, 10);
        if (isNaN(val)) {
          currentMin = "--";
        } else {
          if (val < 0) val = 0;
          if (val > 59) val = 59;
          currentMin = val.toString().padStart(2, "0");
          text.setValue(currentMin);
        }
        updateTime();
      });
    });
    const updateTime = () => {
      if (currentHour === "--" && currentMin === "--") {
        this.event.time = "";
      } else {
        const h = currentHour === "--" ? "12" : currentHour;
        const m = currentMin === "--" ? "00" : currentMin;
        this.event.time = `${h}:${m}`;
      }
    };
    let titleInput;
    new import_obsidian.Setting(form).setName("Title").setDesc("Give your event a name").addText((text) => {
      text.setPlaceholder("e.g. Team standup, Dentist appointment...");
      text.setValue(this.event.title || "");
      text.onChange((value) => {
        this.event.title = value;
      });
      titleInput = text.inputEl;
      titleInput.addClass("memento-title-input");
    });
    new import_obsidian.Setting(form).setName("Context").setDesc("Additional details about the event").addTextArea((text) => {
      text.setPlaceholder("Add context, notes, or details...");
      text.setValue(this.event.context || "");
      text.onChange((value) => {
        this.event.context = value;
      });
      text.inputEl.addClass("memento-context-input");
      text.inputEl.rows = 3;
    });
    new import_obsidian.Setting(form).setName("Recurrence").setDesc("Does this event repeat?").addDropdown((dropdown) => {
      for (const [value, label] of Object.entries(RECURRENCE_LABELS)) {
        dropdown.addOption(value, label);
      }
      dropdown.setValue(this.event.recurrence || "none");
      dropdown.onChange((value) => {
        this.event.recurrence = value;
      });
    });
    const buttonRow = contentEl.createDiv({ cls: "memento-button-row" });
    const cancelBtn = buttonRow.createEl("button", {
      text: "Cancel",
      cls: "memento-btn memento-btn-secondary"
    });
    cancelBtn.addEventListener("click", () => this.close());
    const submitBtn = buttonRow.createEl("button", {
      text: this.isEditing ? "Save Changes" : "Create Event",
      cls: "memento-btn memento-btn-primary"
    });
    submitBtn.addEventListener("click", () => this.handleSubmit());
    window.setTimeout(() => {
      if (titleInput) titleInput.focus();
    }, 50);
    this.scope.register([], "Enter", (e) => {
      if (activeDocument.activeElement?.tagName !== "TEXTAREA") {
        e.preventDefault();
        this.handleSubmit();
      }
    });
  }
  handleSubmit() {
    if (!this.event.title?.trim()) {
      this.contentEl.addClass("memento-shake");
      window.setTimeout(() => this.contentEl.removeClass("memento-shake"), 500);
      return;
    }
    const fullEvent = {
      id: this.event.id || generateId(),
      date: this.event.date || getTodayStr(),
      time: this.event.time || "",
      title: this.event.title.trim(),
      context: this.event.context?.trim() || "",
      recurrence: this.event.recurrence || "none",
      createdAt: this.event.createdAt || (/* @__PURE__ */ new Date()).toISOString()
    };
    this.onSubmit(fullEvent);
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/TimelineView.ts
var import_obsidian2 = require("obsidian");
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, title, message, onConfirm, confirmText = "Confirm", isWarning = false) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
    this.confirmText = confirmText;
    this.isWarning = isWarning;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    ).addButton((btn) => {
      btn.setButtonText(this.confirmText).onClick(() => {
        this.close();
        this.onConfirm();
      });
      if (this.isWarning) {
        btn.setDestructive();
      } else {
        btn.setCta();
      }
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TimelineView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TIMELINE;
  }
  getDisplayText() {
    return "Event Timeline";
  }
  getIcon() {
    return "calendar-clock";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  /**
   * Full re-render of the timeline
   */
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("memento-timeline-container");
    const entries = getTimelineEntries(
      this.plugin.settings.events,
      this.plugin.settings.timelineViewMode
    );
    if (entries.length === 0) {
      this.renderEmptyState(contentEl);
      return;
    }
    const timelineWrapper = contentEl.createDiv({
      cls: "memento-timeline-wrapper"
    });
    const ul = timelineWrapper.createEl("ul", { cls: "memento-timeline" });
    for (const entry of entries) {
      const eventLi = ul.createEl("li", { cls: "memento-tl-event" });
      eventLi.addEventListener("click", () => {
        void (async () => {
          const filePath = this.plugin.getEventNotePath(
            entry.event,
            entry.occurrenceDate
          );
          const fileExists = await this.plugin.app.vault.adapter.exists(filePath);
          if (fileExists) {
            await this.plugin.createNoteForEvent(
              entry.event,
              entry.occurrenceDate
            );
          } else {
            new ConfirmModal(
              this.plugin.app,
              "Create Note",
              `Do you want to create a new note for "${entry.event.title}"?`,
              () => {
                void this.plugin.createNoteForEvent(
                  entry.event,
                  entry.occurrenceDate
                );
              },
              "Create Note",
              false
            ).open();
          }
        })();
      });
      const deleteBtn = eventLi.createDiv({ cls: "memento-tl-delete-btn" });
      (0, import_obsidian2.setIcon)(deleteBtn, "trash-2");
      deleteBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        new ConfirmModal(
          this.plugin.app,
          "Delete Event",
          "Are you sure you want to permanently delete this event?",
          () => {
            void (async () => {
              this.plugin.settings.events = this.plugin.settings.events.filter(
                (ev) => ev.id !== entry.event.id
              );
              await this.plugin.saveSettings();
              this.render();
            })();
          },
          "Delete",
          true
        ).open();
      });
      const contentDiv = eventLi.createDiv({ cls: "memento-tl-content" });
      const dateDiv = contentDiv.createDiv({ cls: "memento-tl-date" });
      const dateLabel = formatDateDisplay(entry.occurrenceDate);
      dateDiv.createSpan({
        text: dateLabel,
        cls: "memento-tl-date-text main-date"
      });
      if (entry.event.time) {
        const timeDiv = contentDiv.createDiv({ cls: "memento-tl-time" });
        timeDiv.createSpan({
          text: formatTimeDisplay(entry.event.time),
          cls: "memento-tl-time-text"
        });
        if (entry.event.recurrence !== "none") {
          timeDiv.createSpan({
            text: RECURRENCE_LABELS[entry.event.recurrence],
            cls: "memento-tl-recurrence-badge"
          });
        }
      } else if (entry.event.recurrence !== "none") {
        const timeDiv = contentDiv.createDiv({ cls: "memento-tl-time" });
        timeDiv.createSpan({
          text: RECURRENCE_LABELS[entry.event.recurrence],
          cls: "memento-tl-recurrence-badge"
        });
      }
      const today = /* @__PURE__ */ new Date();
      const todayStr = `${today.getFullYear()}-${(today.getMonth() + 1).toString().padStart(2, "0")}-${today.getDate().toString().padStart(2, "0")}`;
      const eventDate = /* @__PURE__ */ new Date(entry.occurrenceDate + "T00:00:00");
      const diffTime = eventDate.getTime() - (/* @__PURE__ */ new Date(todayStr + "T00:00:00")).getTime();
      const diffDays = Math.round(diffTime / (1e3 * 60 * 60 * 24));
      let remainingText = "";
      if (diffDays === 0) {
        remainingText = "(Today)";
      } else if (diffDays === 1) {
        remainingText = "(Tomorrow)";
      } else if (diffDays > 1) {
        remainingText = `(${diffDays} days remaining)`;
      } else if (diffDays < 0) {
        remainingText = `(${-diffDays} days ago)`;
      }
      if (remainingText) {
        const remainingDiv = contentDiv.createDiv({
          cls: "memento-tl-remaining"
        });
        remainingDiv.createEl("em", { text: remainingText });
      }
      const titleDiv = contentDiv.createDiv({ cls: "memento-tl-title" });
      titleDiv.createSpan({
        text: entry.event.title,
        cls: "memento-tl-title-text"
      });
      if (entry.event.context) {
        const contextDiv = contentDiv.createDiv({ cls: "memento-tl-context" });
        contextDiv.createEl("p", { text: entry.event.context });
      }
    }
  }
  /**
   * Render empty state when no events exist
   */
  renderEmptyState(container) {
    const empty = container.createDiv({ cls: "memento-empty-state" });
    const iconDiv = empty.createDiv({ cls: "memento-empty-icon" });
    (0, import_obsidian2.setIcon)(iconDiv, "calendar-days");
    empty.createEl("h3", { text: "No upcoming events" });
    empty.createEl("p", {
      text: "Right-click a day in the calendar or use the command palette to create your first event.",
      cls: "memento-empty-desc"
    });
  }
  /**
   * Group timeline entries by date
   */
  groupByDate(entries) {
    const map = /* @__PURE__ */ new Map();
    for (const entry of entries) {
      const existing = map.get(entry.occurrenceDate);
      if (existing) {
        existing.push(entry);
      } else {
        map.set(entry.occurrenceDate, [entry]);
      }
    }
    return map;
  }
};

// src/CalendarDecorator.ts
var import_obsidian3 = require("obsidian");
var CalendarDecorator = class {
  constructor(plugin) {
    this.observer = null;
    this.decorationTimeoutId = null;
    this.addBtnOverlay = null;
    this.currentHoverDate = null;
    this.mouseMoveHandler = this.onMouseMove.bind(this);
    this.contextMenuHandler = this.onContextMenu.bind(this);
    this.plugin = plugin;
  }
  /**
   * Start observing the workspace for Calendar plugin views
   */
  start() {
    this.createAddButtonOverlay();
    this.plugin.registerEvent(
      this.plugin.app.workspace.on("layout-change", () => {
        this.scheduleDecoration();
      })
    );
    this.setupDomObserver();
    window.addEventListener("mousemove", this.mouseMoveHandler, {
      passive: true
    });
    window.addEventListener("contextmenu", this.contextMenuHandler, true);
    this.plugin.register(() => {
      window.removeEventListener("mousemove", this.mouseMoveHandler);
      window.removeEventListener("contextmenu", this.contextMenuHandler, true);
      if (this.addBtnOverlay) {
        this.addBtnOverlay.remove();
        this.addBtnOverlay = null;
      }
    });
    this.scheduleDecoration();
  }
  /**
   * Creates a single floating add button in the document body.
   */
  createAddButtonOverlay() {
    if (this.addBtnOverlay) return;
    this.addBtnOverlay = activeDocument.createElement("div");
    this.addBtnOverlay.className = "memento-add-btn memento-floating-btn";
    this.addBtnOverlay.setText("+");
    this.addBtnOverlay.setAttribute("aria-label", "Create Event");
    this.addBtnOverlay.setCssStyles({ display: "none" });
    activeDocument.body.appendChild(this.addBtnOverlay);
    this.addBtnOverlay.addEventListener("click", (e) => {
      e.stopPropagation();
      e.preventDefault();
      if (this.currentHoverDate) {
        this.plugin.createEventForDate(this.currentHoverDate);
      }
    });
  }
  /**
   * Intercepts right clicks on calendar days globally using the capture phase.
   */
  onContextMenu(e) {
    const target = e.target;
    if (!target || !target.closest) return;
    const dayCell = target.closest(".day");
    if (dayCell && !dayCell.hasClass("adjacent-month")) {
      const leafContent = dayCell.closest(".workspace-leaf-content") || dayCell.closest(".workspace-leaf");
      if (leafContent) {
        const dateStr = this.extractDateFromCell(
          dayCell,
          leafContent
        );
        if (dateStr) {
          e.preventDefault();
          e.stopImmediatePropagation();
          const menu = new import_obsidian3.Menu();
          menu.addItem((item) => {
            item.setTitle("\u{1F4C5} Create Event").setIcon("calendar-plus").onClick(() => {
              this.plugin.createEventForDate(dateStr);
            });
          });
          const eventsOnDate = this.plugin.settings.events.filter(
            (ev) => ev.date === dateStr || ev.recurrence !== "none"
          );
          if (eventsOnDate.length > 0) {
            menu.addSeparator();
            menu.addItem((item) => {
              item.setTitle("\u{1F4CB} View Events Timeline").setIcon("list").onClick(() => {
                void this.plugin.activateTimelineView();
              });
            });
          }
          menu.showAtMouseEvent(e);
        }
      }
    }
  }
  /**
   * Tracks the mouse to see if we are hovering over a calendar day cell.
   */
  onMouseMove(e) {
    const target = e.target;
    if (!target || !target.closest) return;
    if (this.addBtnOverlay && (target === this.addBtnOverlay || this.addBtnOverlay.contains(target))) {
      return;
    }
    const dayCell = target.closest(".day");
    if (dayCell && !dayCell.hasClass("adjacent-month")) {
      const leafContent = dayCell.closest(".workspace-leaf-content") || dayCell.closest(".workspace-leaf");
      if (leafContent) {
        const dateStr = this.extractDateFromCell(
          dayCell,
          leafContent
        );
        if (dateStr && this.addBtnOverlay) {
          this.currentHoverDate = dateStr;
          const rect = dayCell.getBoundingClientRect();
          this.addBtnOverlay.setCssStyles({
            display: "flex",
            top: `${rect.top + 2}px`,
            left: `${rect.left + 2}px`
          });
          return;
        }
      }
    }
    if (this.addBtnOverlay) {
      this.addBtnOverlay.setCssStyles({ display: "none" });
      this.currentHoverDate = null;
    }
  }
  /**
   * Schedule decoration with a small debounce to avoid excessive DOM manipulation
   */
  scheduleDecoration() {
    if (this.decorationTimeoutId !== null) {
      window.clearTimeout(this.decorationTimeoutId);
    }
    this.decorationTimeoutId = window.setTimeout(() => {
      this.decorateCalendar();
      this.decorationTimeoutId = null;
    }, 100);
  }
  /**
   * Set up a MutationObserver on the workspace to detect calendar DOM changes
   */
  setupDomObserver() {
    if (this.observer) {
      this.observer.disconnect();
    }
    this.observer = new MutationObserver(() => {
      this.scheduleDecoration();
    });
    const workspaceEl = activeDocument.querySelector(".workspace");
    if (workspaceEl) {
      this.observer.observe(workspaceEl, {
        childList: true,
        subtree: true,
        attributes: false,
        characterData: false
      });
    }
    this.plugin.register(() => {
      if (this.observer) {
        this.observer.disconnect();
        this.observer = null;
      }
    });
  }
  /**
   * Find the Calendar plugin view and decorate its day cells
   */
  decorateCalendar() {
    const calendarLeaves = this.plugin.app.workspace.getLeavesOfType("calendar");
    if (calendarLeaves.length === 0) return;
    const eventDates = getEventDatesSet(
      this.plugin.settings.events,
      730
      // 2 years lookahead for calendar highlights
    );
    for (const leaf of calendarLeaves) {
      this.decorateLeaf(leaf, eventDates);
    }
  }
  /**
   * Decorate a single calendar leaf's day cells.
   * Only sets up the border highlighting now, as the Add button is handled globally.
   */
  decorateLeaf(leaf, eventDates) {
    const container = leaf.view.containerEl;
    if (!container) return;
    const dayCells = container.querySelectorAll(".day");
    for (const cell of Array.from(dayCells)) {
      const dayEl = cell;
      const dateStr = this.extractDateFromCell(dayEl, container);
      if (!dateStr) continue;
      if (eventDates.has(dateStr)) {
        dayEl.addClass("has-memento-event");
      } else {
        dayEl.removeClass("has-memento-event");
      }
    }
  }
  /**
   * Extract the date string from a calendar day cell.
   * The calendar renders a grid, and we extract the month/year robustly from the container's text.
   */
  extractDateFromCell(cell, container) {
    const dayText = cell.textContent?.trim();
    if (!dayText) return null;
    const dayNum = parseInt(dayText, 10);
    if (isNaN(dayNum) || dayNum < 1 || dayNum > 31) return null;
    let month = (/* @__PURE__ */ new Date()).getMonth() + 1;
    let year = (/* @__PURE__ */ new Date()).getFullYear();
    const monthEl = container.querySelector(".title .month");
    const yearEl = container.querySelector(".title .year");
    if (monthEl && yearEl) {
      const mText = monthEl.textContent?.trim() || "";
      const yText = yearEl.textContent?.trim() || "";
      const parsedY = parseInt(yText, 10);
      if (!isNaN(parsedY)) {
        year = parsedY;
      }
      const mNum = this.getMonthNumber(mText);
      if (mNum > 0) {
        month = mNum;
      }
    } else {
      const containerText = container.innerText || container.textContent || "";
      const parsedMonthYear = this.parseMonthYearRobust(containerText);
      if (parsedMonthYear) {
        month = parsedMonthYear.month;
        year = parsedMonthYear.year;
      }
    }
    const isAdjacentMonth = cell.hasClass("adjacent-month") || cell.hasClass("previous-month") || cell.hasClass("next-month");
    if (isAdjacentMonth) {
      if (dayNum > 20) {
        month -= 1;
        if (month < 1) {
          month = 12;
          year -= 1;
        }
      } else {
        month += 1;
        if (month > 12) {
          month = 1;
          year += 1;
        }
      }
    }
    return `${year}-${month.toString().padStart(2, "0")}-${dayNum.toString().padStart(2, "0")}`;
  }
  getMonthNumber(monthStr) {
    if (!monthStr) return 0;
    const clean = monthStr.replace(/\./g, "").trim().toLowerCase();
    const monthNamesEn = [
      "january",
      "february",
      "march",
      "april",
      "may",
      "june",
      "july",
      "august",
      "september",
      "october",
      "november",
      "december"
    ];
    const monthNamesEs = [
      "enero",
      "febrero",
      "marzo",
      "abril",
      "mayo",
      "junio",
      "julio",
      "agosto",
      "septiembre",
      "octubre",
      "noviembre",
      "diciembre"
    ];
    const monthNamesShortEn = [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec"
    ];
    const monthNamesShortEs = [
      "ene",
      "feb",
      "mar",
      "abr",
      "may",
      "jun",
      "jul",
      "ago",
      "sep",
      "oct",
      "nov",
      "dic"
    ];
    let m = monthNamesEn.indexOf(clean) + 1;
    if (m === 0) m = monthNamesEs.indexOf(clean) + 1;
    if (m === 0) m = monthNamesShortEn.indexOf(clean) + 1;
    if (m === 0) m = monthNamesShortEs.indexOf(clean) + 1;
    if (m > 0) return m;
    if (window.moment) {
      const parsed = window.moment(clean, ["MMM", "MMMM"], true);
      if (parsed.isValid()) return parsed.month() + 1;
      const parsedLoose = window.moment(clean, ["MMM", "MMMM"]);
      if (parsedLoose.isValid()) return parsedLoose.month() + 1;
    }
    return 0;
  }
  parseMonthYearRobust(text) {
    const cleanText = text.toLowerCase().replace(/[,.]/g, " ").replace(/\s+/g, " ");
    const monthNamesEn = [
      "january",
      "february",
      "march",
      "april",
      "may",
      "june",
      "july",
      "august",
      "september",
      "october",
      "november",
      "december"
    ];
    const monthNamesEs = [
      "enero",
      "febrero",
      "marzo",
      "abril",
      "mayo",
      "junio",
      "julio",
      "agosto",
      "septiembre",
      "octubre",
      "noviembre",
      "diciembre"
    ];
    const monthNamesShortEn = [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec"
    ];
    const monthNamesShortEs = [
      "ene",
      "feb",
      "mar",
      "abr",
      "may",
      "jun",
      "jul",
      "ago",
      "sep",
      "oct",
      "nov",
      "dic"
    ];
    const allMonths = [
      ...monthNamesEn,
      ...monthNamesEs,
      ...monthNamesShortEn,
      ...monthNamesShortEs
    ];
    for (const m of allMonths) {
      const regex1 = new RegExp(`\\b${m}\\s+(?:de\\s+)?(20\\d\\d)\\b`);
      const match1 = cleanText.match(regex1);
      if (match1)
        return { month: this.getMonthNumber(m), year: parseInt(match1[1], 10) };
      const regex2 = new RegExp(`\\b(20\\d\\d)\\s+(?:de\\s+)?${m}\\b`);
      const match2 = cleanText.match(regex2);
      if (match2)
        return { month: this.getMonthNumber(m), year: parseInt(match2[1], 10) };
    }
    const numMatch1 = cleanText.match(/\b(20\d\d)[-/ ](\d{1,2})\b/);
    if (numMatch1) {
      const m = parseInt(numMatch1[2], 10);
      if (m >= 1 && m <= 12)
        return { month: m, year: parseInt(numMatch1[1], 10) };
    }
    const numMatch2 = cleanText.match(/\b(\d{1,2})[-/ ](20\d\d)\b/);
    if (numMatch2) {
      const m = parseInt(numMatch2[1], 10);
      if (m >= 1 && m <= 12)
        return { month: m, year: parseInt(numMatch2[2], 10) };
    }
    return null;
  }
  /**
   * Handle right-click on a day cell
   */
  onDayContextMenu(e, dateStr) {
    const menu = new import_obsidian3.Menu();
    menu.addItem((item) => {
      item.setTitle("\u{1F4C5} Create Event").setIcon("calendar-plus").onClick(() => {
        this.plugin.createEventForDate(dateStr);
      });
    });
    const eventsOnDate = this.plugin.settings.events.filter(
      (ev) => ev.date === dateStr || ev.recurrence !== "none"
    );
    if (eventsOnDate.length > 0) {
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("\u{1F4CB} View Events").setIcon("list").onClick(() => {
          void this.plugin.activateTimelineView();
        });
      });
    }
    menu.showAtMouseEvent(e);
  }
  /**
   * Force refresh decorations (called after event changes)
   */
  refresh() {
    this.scheduleDecoration();
  }
  /**
   * Clean up
   */
  destroy() {
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }
    if (this.decorationTimeoutId !== null) {
      window.clearTimeout(this.decorationTimeoutId);
    }
    const cells = activeDocument.querySelectorAll(".has-memento-event");
    cells.forEach((cell) => cell.removeClass("has-memento-event"));
  }
};

// src/EventSettingsTab.ts
var import_obsidian4 = require("obsidian");
var EventSettingsTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    this.render();
  }
  render() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("memento-settings");
    new import_obsidian4.Setting(containerEl).setName("Timeline view mode").setDesc("Choose which events to show in the timeline view").addDropdown(
      (dropdown) => dropdown.addOption("all", "Show all upcoming events").addOption("month", "Show events for current month only").setValue(this.plugin.settings.timelineViewMode).onChange(async (value) => {
        this.plugin.settings.timelineViewMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show past events").setDesc("Display expired one-time events in the list below").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showPastEventsInSettings).onChange(async (value) => {
        this.plugin.settings.showPastEventsInSettings = value;
        void this.plugin.saveSettings().then(() => this.render());
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Frontmatter language").setDesc("Language for the properties when creating a note from an event").addDropdown(
      (dropdown) => dropdown.addOption("en", "English (Title, Date, Context)").addOption("es", "Spanish (T\xEDtulo, Fecha, Contexto)").setValue(this.plugin.settings.frontmatterLanguage).onChange(async (value) => {
        this.plugin.settings.frontmatterLanguage = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Event notes folder").setDesc(
      "Folder where event notes will be created. Leave empty for vault root."
    ).addText(
      (text) => text.setPlaceholder("e.g. Calendar/Events").setValue(this.plugin.settings.eventNoteFolder).onChange(async (value) => {
        this.plugin.settings.eventNoteFolder = value;
        await this.plugin.saveSettings();
      })
    );
    const eventsHeading = new import_obsidian4.Setting(containerEl).setName("Events").setHeading();
    eventsHeading.settingEl.addClass("memento-settings-events-heading");
    new import_obsidian4.Setting(containerEl).setName("Create a new event").setDesc("Add a new event to your calendar").addButton(
      (button) => button.setButtonText("+ Add Event").setCta().onClick(() => {
        new EventModal(this.app, (event) => {
          this.plugin.settings.events.push(event);
          void this.plugin.saveSettings().then(() => this.render());
        }).open();
      })
    );
    const events = this.getFilteredEvents();
    if (events.length === 0) {
      const emptyDiv = containerEl.createDiv({ cls: "memento-settings-empty" });
      emptyDiv.createEl("p", {
        text: "No events yet. Create your first event above!",
        cls: "setting-item-description"
      });
    } else {
      const eventsContainer = containerEl.createDiv({
        cls: "memento-settings-events"
      });
      for (const event of events) {
        this.renderEventItem(eventsContainer, event);
      }
    }
    if (this.plugin.settings.events.length > 0) {
      const dangerHeading = new import_obsidian4.Setting(containerEl).setName("Danger Zone").setHeading();
      dangerHeading.settingEl.addClass("memento-settings-danger-heading");
      new import_obsidian4.Setting(containerEl).setName("Delete all events").setDesc("Permanently remove all events. This cannot be undone.").addButton(
        (button) => button.setButtonText("Delete All").setDestructive().onClick(() => {
          this.plugin.settings.events = [];
          void this.plugin.saveSettings().then(() => this.render());
        })
      );
    }
  }
  /**
   * Get events filtered based on settings
   */
  getFilteredEvents() {
    let events = [...this.plugin.settings.events];
    if (!this.plugin.settings.showPastEventsInSettings) {
      const today = /* @__PURE__ */ new Date();
      const todayStr = `${today.getFullYear()}-${(today.getMonth() + 1).toString().padStart(2, "0")}-${today.getDate().toString().padStart(2, "0")}`;
      events = events.filter((e) => {
        if (e.recurrence !== "none") return true;
        return e.date >= todayStr;
      });
    }
    events.sort((a, b) => a.date.localeCompare(b.date));
    return events;
  }
  /**
   * Render a single event item in the settings list
   */
  renderEventItem(container, event) {
    const eventEl = container.createDiv({ cls: "memento-settings-event" });
    const infoEl = eventEl.createDiv({ cls: "memento-settings-event-info" });
    const titleRow = infoEl.createDiv({
      cls: "memento-settings-event-title-row"
    });
    titleRow.createSpan({
      text: event.title,
      cls: "memento-settings-event-title"
    });
    if (event.recurrence !== "none") {
      titleRow.createSpan({
        text: RECURRENCE_LABELS[event.recurrence],
        cls: "memento-settings-event-badge"
      });
    }
    const metaRow = infoEl.createDiv({ cls: "memento-settings-event-meta" });
    metaRow.createSpan({
      text: formatDateDisplay(event.date),
      cls: "memento-settings-event-date"
    });
    if (event.time) {
      metaRow.createSpan({ text: " \xB7 " });
      metaRow.createSpan({
        text: formatTimeDisplay(event.time),
        cls: "memento-settings-event-time"
      });
    }
    if (event.context) {
      infoEl.createEl("p", {
        text: event.context,
        cls: "memento-settings-event-context"
      });
    }
    const actionsEl = eventEl.createDiv({
      cls: "memento-settings-event-actions"
    });
    const editBtn = actionsEl.createEl("button", {
      cls: "memento-settings-btn memento-settings-btn-edit",
      attr: { "aria-label": "Edit event" }
    });
    (0, import_obsidian4.setIcon)(editBtn, "pencil");
    editBtn.addEventListener("click", () => {
      new EventModal(
        this.app,
        (updatedEvent) => {
          const idx = this.plugin.settings.events.findIndex(
            (e) => e.id === event.id
          );
          if (idx !== -1) {
            this.plugin.settings.events[idx] = updatedEvent;
            void this.plugin.saveSettings().then(() => this.render());
          }
        },
        event
      ).open();
    });
    const deleteBtn = actionsEl.createEl("button", {
      cls: "memento-settings-btn memento-settings-btn-delete",
      attr: { "aria-label": "Delete event" }
    });
    (0, import_obsidian4.setIcon)(deleteBtn, "trash-2");
    deleteBtn.addEventListener("click", () => {
      this.plugin.settings.events = this.plugin.settings.events.filter(
        (e) => e.id !== event.id
      );
      void this.plugin.saveSettings().then(() => this.render());
    });
  }
};

// src/main.ts
var MementoPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_TIMELINE, (leaf) => {
      return new TimelineView(leaf, this);
    });
    this.addSettingTab(new EventSettingsTab(this.app, this));
    this.decorator = new CalendarDecorator(this);
    this.addCommand({
      id: "create-event",
      name: "Create a new event",
      callback: () => {
        void this.openCreateEventModal();
      }
    });
    this.addCommand({
      id: "create-event-today",
      name: "Create event for today",
      callback: () => {
        void this.createEventForDate(this.getTodayStr());
      }
    });
    this.addCommand({
      id: "open-timeline",
      name: "Open event timeline",
      callback: () => {
        void this.activateTimelineView();
      }
    });
    this.addRibbonIcon("calendar-clock", "Memento \u2014 Event Timeline", () => {
      void this.activateTimelineView();
    });
    this.app.workspace.onLayoutReady(() => {
      this.decorator.start();
      void this.activateTimelineView();
    });
    this.registerInterval(
      window.setInterval(() => {
        this.refreshTimeline();
        this.decorator.refresh();
      }, 60 * 1e3)
    );
  }
  onunload() {
    if (this.decorator) {
      this.decorator.destroy();
    }
    this.app.workspace.getLeavesOfType(VIEW_TYPE_TIMELINE).forEach((leaf) => {
      leaf.detach();
    });
  }
  // ─── Settings Persistence ────────────────────────────────────────
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data || {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshTimeline();
    this.decorator?.refresh();
  }
  // ─── Event Management ────────────────────────────────────────────
  /**
   * Open the create event modal (no date pre-filled — user picks)
   */
  openCreateEventModal() {
    new EventModal(this.app, (event) => {
      this.settings.events.push(event);
      void this.saveSettings();
    }).open();
  }
  /**
   * Open the create event modal for a specific date
   */
  createEventForDate(dateStr) {
    new EventModal(
      this.app,
      (event) => {
        this.settings.events.push(event);
        void this.saveSettings();
      },
      void 0,
      dateStr
    ).open();
  }
  getEventNotePath(event, occurrenceDate) {
    const folderPath = this.settings.eventNoteFolder.trim();
    const safeTitle = event.title.replace(/[\\/:"*?<>|#^[\]]/g, "").trim();
    const filename = `${occurrenceDate} - ${safeTitle}.md`;
    return folderPath ? `${folderPath}/${filename}` : filename;
  }
  /**
   * Create or open a note for a specific event
   */
  async createNoteForEvent(event, occurrenceDate) {
    const { vault, workspace } = this.app;
    const folderPath = this.settings.eventNoteFolder.trim();
    if (folderPath !== "") {
      const folderExists = await vault.adapter.exists(folderPath);
      if (!folderExists) {
        await vault.createFolder(folderPath);
      }
    }
    const filePath = this.getEventNotePath(event, occurrenceDate);
    const abstractFile = vault.getAbstractFileByPath(filePath);
    let file = null;
    if (abstractFile instanceof import_obsidian5.TFile) {
      file = abstractFile;
    }
    if (!file) {
      const isEs = this.settings.frontmatterLanguage === "es";
      const titleKey = isEs ? "T\xEDtulo" : "Title";
      const dateKey = isEs ? "Fecha" : "Date";
      const contextKey = isEs ? "Contexto" : "Context";
      const dateTimeStr = event.time ? `${occurrenceDate} ${event.time}` : occurrenceDate;
      const safeTitleVal = event.title.replace(/"/g, '\\"');
      const safeContextVal = event.context ? event.context.replace(/"/g, '\\"').replace(/\n/g, "\\n") : "";
      let content = `---
`;
      content += `${titleKey}: "${safeTitleVal}"
`;
      content += `${dateKey}: ${dateTimeStr}
`;
      if (safeContextVal) {
        content += `${contextKey}: "${safeContextVal}"
`;
      } else {
        content += `${contextKey}: ""
`;
      }
      content += `---

# ${event.title}
`;
      file = await vault.create(filePath, content);
    }
    const leaf = workspace.getLeaf(false);
    await leaf.openFile(file);
  }
  // ─── Timeline View ───────────────────────────────────────────────
  /**
   * Activate (open/reveal) the timeline view in the right sidebar
   */
  async activateTimelineView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_TIMELINE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({
          type: VIEW_TYPE_TIMELINE,
          active: true
        });
        leaf = rightLeaf;
      }
    }
    if (leaf) {
      void workspace.revealLeaf(leaf);
    }
  }
  /**
   * Refresh the timeline view contents
   */
  refreshTimeline() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TIMELINE);
    for (const leaf of leaves) {
      if (leaf.view instanceof TimelineView) {
        leaf.view.render();
      }
    }
  }
  // ─── Utilities ───────────────────────────────────────────────────
  getTodayStr() {
    const d = /* @__PURE__ */ new Date();
    return `${d.getFullYear()}-${(d.getMonth() + 1).toString().padStart(2, "0")}-${d.getDate().toString().padStart(2, "0")}`;
  }
};
